export interface CommonIngredientDefinition {
  id: string;
  aliases: string[];
  name: string;
  servingLabel: string;
  servingGrams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  priority?: number;
  extraPortions?: Array<{ id: string; label: string; amount: number; grams: number }>;
}

export const COMMON_INGREDIENT_CATALOG: CommonIngredientDefinition[] = [
  { id: 'egg_large', aliases: ['egg', 'whole egg', 'large egg'], name: 'Egg, whole, large', servingLabel: '1 large egg', servingGrams: 50, calories: 72, protein: 6.3, carbs: 0.4, fat: 4.8, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'egg_white_large', aliases: ['egg white', 'egg whites'], name: 'Egg whites', servingLabel: '3 large egg whites', servingGrams: 99, calories: 51, protein: 10.8, carbs: 0.7, fat: 0.2, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'banana_medium', aliases: ['banana'], name: 'Banana, medium', servingLabel: '1 medium banana', servingGrams: 118, calories: 105, protein: 1.3, carbs: 27, fat: 0.4, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'apple_medium', aliases: ['apple'], name: 'Apple, medium', servingLabel: '1 medium apple', servingGrams: 182, calories: 95, protein: 0.5, carbs: 25, fat: 0.3, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'orange_medium', aliases: ['orange'], name: 'Orange, medium', servingLabel: '1 medium orange', servingGrams: 131, calories: 62, protein: 1.2, carbs: 15.4, fat: 0.2, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'mango_cup', aliases: ['mango'], name: 'Mango, sliced', servingLabel: '1 cup', servingGrams: 165, calories: 99, protein: 1.4, carbs: 24.7, fat: 0.6, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'pineapple_cup', aliases: ['pineapple'], name: 'Pineapple chunks', servingLabel: '1 cup', servingGrams: 165, calories: 82, protein: 0.9, carbs: 21.6, fat: 0.2, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'grapes_cup', aliases: ['grape', 'grapes'], name: 'Grapes', servingLabel: '1 cup', servingGrams: 151, calories: 104, protein: 1.1, carbs: 27.3, fat: 0.2, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'blueberries_cup', aliases: ['blueberry', 'blueberries'], name: 'Blueberries', servingLabel: '1 cup', servingGrams: 148, calories: 84, protein: 1.1, carbs: 21.4, fat: 0.5, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'raspberries_cup', aliases: ['raspberry', 'raspberries'], name: 'Raspberries', servingLabel: '1 cup', servingGrams: 123, calories: 64, protein: 1.5, carbs: 14.7, fat: 0.8, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'strawberries_cup', aliases: ['strawberry', 'strawberries'], name: 'Strawberries', servingLabel: '1 cup', servingGrams: 152, calories: 49, protein: 1, carbs: 11.7, fat: 0.5, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'kiwi_green', aliases: ['kiwi', 'kiwifruit'], name: 'Kiwi fruit, green', servingLabel: '1 medium kiwi', servingGrams: 69, calories: 42, protein: 0.8, carbs: 10.1, fat: 0.4, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'kiwi_gold', aliases: ['gold kiwi'], name: 'Kiwi fruit, gold', servingLabel: '1 medium kiwi', servingGrams: 69, calories: 45, protein: 0.9, carbs: 11, fat: 0.3, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'avocado_half', aliases: ['avocado'], name: 'Avocado', servingLabel: '1/2 medium avocado', servingGrams: 75, calories: 120, protein: 1.5, carbs: 6.4, fat: 11, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'greek_yogurt_plain_nonfat', aliases: ['yogurt', 'greek yogurt', 'plain yogurt', 'plain greek yogurt', 'nonfat greek yogurt'], name: 'Greek yogurt, plain, nonfat', servingLabel: '3/4 cup', servingGrams: 170, calories: 100, protein: 17, carbs: 6, fat: 0, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'greek_yogurt_plain_2pct', aliases: ['2% greek yogurt', 'greek yogurt'], name: 'Greek yogurt, plain, 2%', servingLabel: '3/4 cup', servingGrams: 170, calories: 140, protein: 15, carbs: 6, fat: 4, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'yogurt_plain_lowfat', aliases: ['yogurt', 'plain yogurt'], name: 'Yogurt, plain, lowfat', servingLabel: '1 cup', servingGrams: 245, calories: 154, protein: 13, carbs: 17, fat: 4, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'cottage_cheese_cup', aliases: ['cottage cheese'], name: 'Cottage cheese, lowfat', servingLabel: '1 cup', servingGrams: 226, calories: 180, protein: 24, carbs: 8, fat: 5, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'milk_2pct_cup', aliases: ['milk', '2% milk'], name: 'Milk, 2%', servingLabel: '1 cup', servingGrams: 244, calories: 122, protein: 8.1, carbs: 12, fat: 4.8, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'almond_milk_cup', aliases: ['almond milk'], name: 'Almond milk, unsweetened', servingLabel: '1 cup', servingGrams: 240, calories: 30, protein: 1, carbs: 1, fat: 2.5, priority: 6, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'white_rice_cup', aliases: ['rice', 'white rice', 'cooked white rice'], name: 'White rice, cooked', servingLabel: '1 cup cooked', servingGrams: 158, calories: 205, protein: 4.3, carbs: 44.5, fat: 0.4, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'brown_rice_cup', aliases: ['rice', 'brown rice'], name: 'Brown rice, cooked', servingLabel: '1 cup cooked', servingGrams: 195, calories: 216, protein: 5, carbs: 45, fat: 1.8, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'jasmine_rice_cup', aliases: ['rice', 'jasmine rice'], name: 'Jasmine rice, cooked', servingLabel: '1 cup cooked', servingGrams: 140, calories: 205, protein: 4.2, carbs: 45, fat: 0.4, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'basmati_rice_cup', aliases: ['rice', 'basmati rice'], name: 'Basmati rice, cooked', servingLabel: '1 cup cooked', servingGrams: 163, calories: 190, protein: 4.4, carbs: 39.5, fat: 0.6, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'rice_pudding_half_cup', aliases: ['rice pudding'], name: 'Rice pudding', servingLabel: '1/2 cup', servingGrams: 120, calories: 150, protein: 3.5, carbs: 27, fat: 3.2, priority: 6, extraPortions: [{ id: 'cup', label: '1 cup', amount: 1, grams: 240 }] },
  { id: 'rolled_oats_half_cup', aliases: ['oatmeal', 'oats', 'rolled oats', 'old fashioned oats'], name: 'Rolled oats, dry', servingLabel: '1/2 cup dry', servingGrams: 40, calories: 150, protein: 5, carbs: 27, fat: 3, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'oatmeal_cup', aliases: ['oatmeal', 'cooked oatmeal'], name: 'Oatmeal, cooked', servingLabel: '1 cup cooked', servingGrams: 234, calories: 166, protein: 5.9, carbs: 28.1, fat: 3.6, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'quinoa_cup', aliases: ['quinoa'], name: 'Quinoa, cooked', servingLabel: '1 cup cooked', servingGrams: 185, calories: 222, protein: 8.1, carbs: 39.4, fat: 3.6, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'pasta_cup', aliases: ['pasta'], name: 'Pasta, cooked', servingLabel: '1 cup cooked', servingGrams: 140, calories: 220, protein: 8, carbs: 43, fat: 1.3, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'potato_medium', aliases: ['potato', 'white potato'], name: 'Potato, baked', servingLabel: '1 medium potato', servingGrams: 173, calories: 161, protein: 4.3, carbs: 36.6, fat: 0.2, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'sweet_potato_medium', aliases: ['sweet potato'], name: 'Sweet potato, baked', servingLabel: '1 medium sweet potato', servingGrams: 114, calories: 103, protein: 2.3, carbs: 23.6, fat: 0.2, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'broccoli_cup', aliases: ['broccoli'], name: 'Broccoli, chopped', servingLabel: '1 cup', servingGrams: 91, calories: 31, protein: 2.5, carbs: 6, fat: 0.3, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'spinach_cup', aliases: ['spinach'], name: 'Spinach, raw', servingLabel: '1 cup', servingGrams: 30, calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'carrots_cup', aliases: ['carrot', 'carrots'], name: 'Carrots, chopped', servingLabel: '1 cup', servingGrams: 128, calories: 52, protein: 1.2, carbs: 12.3, fat: 0.3, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'tomato_medium', aliases: ['tomato', 'tomatoes'], name: 'Tomato, medium', servingLabel: '1 medium tomato', servingGrams: 123, calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'chicken_breast_4oz', aliases: ['chicken', 'chicken breast'], name: 'Chicken breast, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 185, protein: 35, carbs: 0, fat: 4, priority: 10, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'chicken_thigh_4oz', aliases: ['chicken', 'chicken thigh'], name: 'Chicken thigh, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 229, protein: 28, carbs: 0, fat: 13, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'chicken_tenderloin_4oz', aliases: ['chicken', 'chicken tenderloin', 'chicken tenders'], name: 'Chicken tenderloin, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 187, protein: 34, carbs: 0, fat: 4.3, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'chicken_drumstick_4oz', aliases: ['chicken', 'chicken drumstick', 'drumstick'], name: 'Chicken drumstick, roasted', servingLabel: '4 oz cooked', servingGrams: 112, calories: 216, protein: 27, carbs: 0, fat: 11, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'pork_loin_4oz', aliases: ['pork', 'pork loin', 'pork tenderloin'], name: 'Pork loin, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 196, protein: 29, carbs: 0, fat: 7, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'pork_chop_4oz', aliases: ['pork', 'pork chop'], name: 'Pork chop, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 231, protein: 29, carbs: 0, fat: 12, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'ground_pork_4oz', aliases: ['pork', 'ground pork'], name: 'Ground pork, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 293, protein: 24, carbs: 0, fat: 21, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'pork_tenderloin_4oz', aliases: ['pork', 'pork tenderloin'], name: 'Pork tenderloin, roasted', servingLabel: '4 oz cooked', servingGrams: 112, calories: 170, protein: 30, carbs: 0, fat: 5, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'salmon_4oz', aliases: ['salmon'], name: 'Salmon, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 233, protein: 25, carbs: 0, fat: 14, priority: 9, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'ground_beef_4oz', aliases: ['beef', 'ground beef'], name: 'Ground beef, lean, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 225, protein: 24, carbs: 0, fat: 14, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'turkey_breast_4oz', aliases: ['turkey', 'turkey breast'], name: 'Turkey breast, roasted', servingLabel: '4 oz cooked', servingGrams: 112, calories: 135, protein: 30, carbs: 0, fat: 1.5, priority: 8, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'shrimp_4oz', aliases: ['shrimp'], name: 'Shrimp, cooked', servingLabel: '4 oz cooked', servingGrams: 112, calories: 112, protein: 24, carbs: 0.3, fat: 1.3, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'tofu_half_block', aliases: ['tofu'], name: 'Tofu, firm', servingLabel: '1/2 block', servingGrams: 126, calories: 144, protein: 15.5, carbs: 3.5, fat: 8.7, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'black_beans_half_cup', aliases: ['black beans', 'beans'], name: 'Black beans, cooked', servingLabel: '1/2 cup', servingGrams: 86, calories: 114, protein: 7.6, carbs: 20.4, fat: 0.5, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'peanut_butter_2tbsp', aliases: ['peanut butter'], name: 'Peanut butter', servingLabel: '2 tbsp', servingGrams: 32, calories: 190, protein: 7, carbs: 7, fat: 16, priority: 8, extraPortions: [{ id: 'tbsp', label: '1 tbsp', amount: 1, grams: 16 }] },
  { id: 'almonds_ounce', aliases: ['almond', 'almonds'], name: 'Almonds', servingLabel: '1 oz', servingGrams: 28, calories: 164, protein: 6, carbs: 6.1, fat: 14.2, priority: 7, extraPortions: [{ id: '100g', label: '100g', amount: 100, grams: 100 }] },
  { id: 'olive_oil_tbsp', aliases: ['olive oil'], name: 'Olive oil', servingLabel: '1 tbsp', servingGrams: 14, calories: 119, protein: 0, carbs: 0, fat: 13.5, priority: 7, extraPortions: [{ id: 'tsp', label: '1 tsp', amount: 1, grams: 4.5 }] },
];
