import type { FightStatus, WeighInTiming } from '../types/foundational.ts';
import type { CutPlanWarning } from '../types/weight_cut.ts';
import {
  ENGINE_SAFETY_POLICY_VERSION,
  type EngineSafetyWarning,
  type EngineSafetyWarningSource,
  type EngineSafetyWarningTier,
} from '../types/safety.ts';

export const FIGHT_CAMP_SAFETY_POLICY = {
  riskScore: {
    moderate: 35,
    high: 55,
    critical: 75,
  },
  intervention: {
    hardIntensityCap: 3,
    softIntensityCap: 5,
    protectIntensityCap: 4,
    expressIntensityFloor: 8,
    constrainedMinDurationMin: 20,
    mandatoryRecoveryMaxDurationMin: 20,
    softMaxDurationMin: 30,
    cutProtectDefaultDurationMin: 25,
    cutProtectMaxDurationMin: 30,
  },
  scheduling: {
    minimumGuidedSessionMin: 20,
  },
  sodium: {
    restrictedTargetMg: 500,
    unsafeInstructionFragments: [
      'water dump',
      'zero sodium',
      'no sodium',
      'minimal sodium',
      'stay away from salt',
    ],
  },
  hydration: {
    fightWeekSupportMultiplier: 1.0,
    fightWeekSupportTargetOz: 96,
  },
} as const;

export function hasUnsafeFightCampSodiumLanguage(value: string | null | undefined): boolean {
  const text = value?.toLowerCase() ?? '';
  return FIGHT_CAMP_SAFETY_POLICY.sodium.unsafeInstructionFragments.some((fragment) =>
    text.includes(fragment),
  );
}

export function isFightCampSodiumRestricted(input: {
  sodiumTargetMg?: number | null;
  sodiumInstruction?: string | null;
}): boolean {
  const sodiumInstruction = input.sodiumInstruction?.toLowerCase() ?? '';
  return (input.sodiumTargetMg != null && input.sodiumTargetMg <= FIGHT_CAMP_SAFETY_POLICY.sodium.restrictedTargetMg)
    || sodiumInstruction.includes('zero')
    || sodiumInstruction.includes('minimal');
}

export function getSafeFightCampSodiumRestrictionDetail(sodiumInstruction: string | null | undefined): string {
  const trimmed = sodiumInstruction?.trim() ?? '';
  if (!trimmed || hasUnsafeFightCampSodiumLanguage(trimmed)) {
    return 'Sodium should stay predictable; use qualified support for any nonstandard fight-week change.';
  }
  return trimmed;
}

export function getFightCampSodiumRestrictionInterpretation(input: {
  sodiumTargetMg?: number | null;
  sodiumInstruction?: string | null;
}): string | null {
  if (!isFightCampSodiumRestricted(input)) return null;
  return 'Sodium is unusually low for this context. Keep intake predictable and escalate to qualified support rather than chasing the scale.';
}

export function getFightWeekLoadHydrationMultiplier(_daysToWeighIn: number): number {
  return FIGHT_CAMP_SAFETY_POLICY.hydration.fightWeekSupportMultiplier;
}

export function getFightWeekLoadHydrationInstruction(oz: number): string {
  return `${oz} oz - keep fluids steady and familiar across the day.`;
}

export function getFightWeekLoadSodiumInstruction(_daysToWeighIn: number): string {
  return 'Normal and predictable.';
}

export function getFightWeekCutWaterTargetOz(_daysToWeighIn: number): number {
  return FIGHT_CAMP_SAFETY_POLICY.hydration.fightWeekSupportTargetOz;
}

export function getFightWeekCutHydrationInstruction(oz: number): string {
  return `${oz} oz baseline support - no acute fluid manipulation is generated by the app.`;
}

export function getFightWeekCutSodiumInstruction(_daysToWeighIn: number): string {
  return 'Normal and predictable; do not chase the scale with unsupervised electrolyte changes.';
}

export function getWeighInHydrationInstruction(): string {
  return 'Follow normal comfort cues and event rules; no app-generated fluid tactics.';
}

export function getWeighInSodiumInstruction(): string {
  return 'Keep sodium familiar and predictable until competition logistics are complete.';
}

export function computeRehydrationFluidTargetLiters(_input: {
  currentWeight: number;
  targetWeight: number;
}): number {
  return 0;
}

function makeWarning(input: {
  code: string;
  tier: EngineSafetyWarningTier;
  message: string;
  requiresAcknowledgement?: boolean;
  persistent?: boolean;
  source?: EngineSafetyWarningSource;
}): EngineSafetyWarning {
  return {
    code: input.code,
    tier: input.tier,
    message: input.message,
    requiresAcknowledgement:
      input.requiresAcknowledgement ?? (input.tier === 'severe' || input.tier === 'medical'),
    persistent:
      input.persistent ?? (input.tier === 'severe' || input.tier === 'medical'),
    allowProceed: true,
    policyVersion: ENGINE_SAFETY_POLICY_VERSION,
    source: input.source ?? 'weight_cut',
  };
}

function tierRank(tier: EngineSafetyWarningTier): number {
  switch (tier) {
    case 'medical': return 4;
    case 'severe': return 3;
    case 'caution': return 2;
    case 'info':
    default: return 1;
  }
}

export function isTeenAthlete(age: number | null | undefined): boolean {
  return typeof age === 'number' && age > 0 && age < 18;
}

export function isAgeUnknown(age: number | null | undefined): boolean {
  return typeof age !== 'number' || age <= 0;
}

export function getPolicyWaterCutPct(_input: {
  fightStatus: FightStatus;
  athleteAge?: number | null;
  weighInTiming?: WeighInTiming | null;
}): number {
  return 0;
}

export function evaluateCutPlanSafety(input: {
  startWeight: number;
  targetWeight: number;
  totalCutLbs: number;
  totalCutPct: number;
  daysToWeighIn: number | null;
  fightStatus: FightStatus;
  athleteAge?: number | null;
  weighInTiming?: WeighInTiming | null;
  waterCutAllocationLbs: number;
  dietPhaseTargetLbs: number;
  dietPhaseDays: number;
}): EngineSafetyWarning[] {
  const warnings: EngineSafetyWarning[] = [];
  const { startWeight, targetWeight, totalCutLbs, totalCutPct, daysToWeighIn, athleteAge, dietPhaseDays } = input;
  const ageUnknown = isAgeUnknown(athleteAge);
  const teen = isTeenAthlete(athleteAge);
  const requiredWeeklyPct = startWeight > 0 && dietPhaseDays > 0
    ? (totalCutLbs / startWeight) / (dietPhaseDays / 7) * 100
    : null;

  if (startWeight <= 0 || targetWeight <= 0 || daysToWeighIn == null) {
    warnings.push(makeWarning({
      code: 'missing_body_mass_context',
      tier: 'caution',
      message: 'Body-mass target feasibility is incomplete; missing data must be treated as unknown.',
      source: 'weight_cut',
      requiresAcknowledgement: false,
    }));
  }

  if (totalCutPct >= 7 || (requiredWeeklyPct != null && requiredWeeklyPct > 1)) {
    warnings.push(makeWarning({
      code: 'weight_class_target_review',
      tier: totalCutPct >= 10 || (requiredWeeklyPct != null && requiredWeeklyPct > 1.5) ? 'medical' : 'severe',
      message:
        `This target requires ${totalCutPct.toFixed(1)}% body-mass change` +
        `${daysToWeighIn == null ? '' : ` in ${daysToWeighIn} day(s)`}. Automatic rapid scale protocols are blocked.`,
      source: 'weight_cut',
      persistent: true,
    }));
  }

  if (teen || ageUnknown) {
    warnings.push(makeWarning({
      code: teen ? 'minor_weight_class_review' : 'unknown_age_weight_class_review',
      tier: teen ? 'medical' : 'caution',
      message: teen
        ? 'Minor athletes require qualified review before body-mass reduction planning.'
        : 'Age is unknown, so the engine keeps body-mass planning conservative.',
      source: 'weight_cut',
      persistent: true,
      requiresAcknowledgement: teen,
    }));
  }

  return warnings.sort((a, b) => tierRank(b.tier) - tierRank(a.tier));
}

export function toCutPlanWarning(input: {
  warning: EngineSafetyWarning;
  fightStatus: FightStatus;
  athleteAge?: number | null;
  daysToWeighIn: number | null;
  cutPct: number;
}): CutPlanWarning {
  return {
    severity: input.warning.tier,
    tier: input.warning.tier,
    code: input.warning.code,
    message: input.warning.message,
    requiresAcknowledgement: input.warning.requiresAcknowledgement,
    persistent: input.warning.persistent,
    allowProceed: input.warning.allowProceed,
    policyVersion: input.warning.policyVersion,
    source: input.warning.source,
    amateurAdjusted: input.fightStatus === 'amateur',
    teenSensitive: isTeenAthlete(input.athleteAge),
    ageUnknown: isAgeUnknown(input.athleteAge),
    daysToWeighIn: input.daysToWeighIn,
    cutPct: input.cutPct,
  };
}
