import type { Exercise, ExerciseMedia } from '../../types.ts';

const contentVersion = '2026.05-p3-expanded-ontology';
const lastUpdatedAt = '2026-05-03T00:00:00.000Z';

function pendingMedia(altText: string): ExerciseMedia {
  return {
    videoUrl: null,
    imageUrl: null,
    thumbnailUrl: null,
    altText,
    reviewStatus: 'needs_review',
  };
}

function reviewMeta(riskLevel: Exercise['riskLevel'] = 'moderate') {
  return {
    reviewStatus: 'needs_review' as const,
    safetyReviewStatus: riskLevel === 'low' ? 'not_required' as const : 'needs_review' as const,
    reviewNotes: ['Expanded P3 ontology candidate. Coach and safety review required before production rollout.'],
    contentVersion,
    lastUpdatedAt,
    riskLevel,
    rolloutEligibility: 'preview' as const,
  };
}

export const expandedLowerBodyExercises = [
  {
    ...reviewMeta('moderate'),
    id: 'hip_thrust',
    name: 'Hip Thrust',
    shortName: 'Hip Thrust',
    category: 'hypertrophy',
    summary: 'Bench-supported hip-extension strength and hypertrophy exercise for glutes.',
    coachingSummary: 'Set the ribs down, drive through the mid-foot, and finish with glutes rather than low-back extension.',
    movementPatternIds: ['hinge'],
    subPatternIds: ['loaded_hip_extension', 'glute_bridge_progression'],
    primaryMuscleIds: ['glutes'],
    secondaryMuscleIds: ['hamstrings', 'core'],
    jointsInvolved: ['hips', 'knees', 'spine'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['bodyweight', 'bench', 'dumbbells', 'barbell'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['bench', 'dumbbells', 'barbell'],
    setupType: 'bench',
    workoutTypeIds: ['strength', 'hypertrophy', 'lower_strength'],
    goalIds: ['hypertrophy', 'dumbbell_hypertrophy', 'lower_body_strength', 'full_gym_strength'],
    minExperience: 'beginner',
    technicalComplexity: 'moderate',
    loadability: 'high',
    fatigueCost: 'moderate',
    intensity: 'moderate',
    impact: 'none',
    spineLoading: 'low',
    kneeDemand: 'low',
    hipDemand: 'high',
    shoulderDemand: 'low',
    wristDemand: 'none',
    ankleDemand: 'low',
    balanceDemand: 'low',
    cardioDemand: 'low',
    spaceRequired: ['small_space'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['glute_bridge'],
    progressionExerciseIds: ['romanian_deadlift', 'trap_bar_deadlift'],
    substitutionExerciseIds: ['glute_bridge', 'romanian_deadlift', 'cable_woodchop'],
    contraindicationFlags: ['back_caution'],
    setupInstructions: [
      'Set the upper back on a bench or stable support and place feet about hip-width.',
      'Start with ribs stacked over the pelvis and choose a load that does not pull the low back into extension.',
    ],
    executionInstructions: [
      'Drive through the mid-foot and extend the hips until the torso is level.',
      'Pause briefly at the top, then lower under control without bouncing off the floor.',
    ],
    breathingInstructions: [
      'Inhale before the lift and brace lightly.',
      'Exhale through the top while keeping ribs down and pelvis controlled.',
    ],
    safetyNotes: [
      'Regress to glute bridge if low-back pressure increases or the top position cannot stay controlled.',
      'Use padding and a stable bench before adding meaningful load.',
    ],
    trackingMetricIds: ['sets_completed', 'reps_completed', 'load_used', 'actual_rpe', 'movement_quality'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 4 },
      reps: { min: 8, max: 15 },
      rpe: { min: 6, max: 8 },
      restSeconds: { min: 60, max: 120 },
    },
    defaultPrescriptionTemplateId: 'hypertrophy_straight',
    media: pendingMedia('Athlete performing a controlled hip thrust with ribs down and feet planted.'),
  },
  {
    ...reviewMeta('moderate'),
    id: 'lateral_lunge',
    name: 'Lateral Lunge',
    shortName: 'Lateral Lunge',
    category: 'strength',
    summary: 'Frontal-plane single-leg pattern for adductors, glutes, quads, and hip control.',
    coachingSummary: 'Shift into the working hip, keep the foot planted, and use only the range you can own.',
    movementPatternIds: ['lunge'],
    subPatternIds: ['frontal_plane_lunge', 'adductor_strength'],
    primaryMuscleIds: ['adductors', 'glutes', 'quads'],
    secondaryMuscleIds: ['hamstrings', 'core'],
    jointsInvolved: ['hips', 'knees', 'ankles'],
    planeOfMotion: 'frontal',
    equipmentIds: ['bodyweight', 'dumbbells', 'kettlebell'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['dumbbells', 'kettlebell'],
    setupType: 'standing',
    workoutTypeIds: ['strength', 'hypertrophy', 'lower_strength', 'mobility'],
    goalIds: ['beginner_strength', 'lower_body_strength', 'hypertrophy', 'mobility'],
    minExperience: 'beginner',
    technicalComplexity: 'moderate',
    loadability: 'moderate',
    fatigueCost: 'moderate',
    intensity: 'moderate',
    impact: 'low',
    spineLoading: 'low',
    kneeDemand: 'moderate',
    hipDemand: 'high',
    shoulderDemand: 'none',
    wristDemand: 'none',
    ankleDemand: 'moderate',
    balanceDemand: 'moderate',
    cardioDemand: 'low',
    spaceRequired: ['small_space'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['split_squat', 'bodyweight_squat'],
    progressionExerciseIds: ['reverse_lunge', 'step_up'],
    substitutionExerciseIds: ['split_squat', 'reverse_lunge', 'step_up'],
    contraindicationFlags: ['knee_caution', 'limited_space'],
    setupInstructions: [
      'Stand tall with enough side-to-side room and feet pointing mostly forward.',
      'Begin bodyweight until hip range, knee tracking, and foot pressure are predictable.',
    ],
    executionInstructions: [
      'Step or shift to the side and sit into the working hip while the other leg lengthens.',
      'Push the floor away to return to the start without twisting the knee inward.',
    ],
    breathingInstructions: [
      'Inhale as you shift into the lunge.',
      'Exhale as you push back to the starting position.',
    ],
    safetyNotes: [
      'Shorten range if knee pressure, groin discomfort, or ankle collapse appears.',
      'Use a squat or supported split squat if balance becomes the limiter.',
    ],
    trackingMetricIds: ['sets_completed', 'reps_completed', 'actual_rpe', 'range_quality', 'movement_quality'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 3 },
      reps: { min: 6, max: 10, unit: 'per_side' },
      rpe: { min: 5, max: 7 },
      restSeconds: { min: 45, max: 90 },
    },
    defaultPrescriptionTemplateId: 'strength_beginner',
    media: pendingMedia('Athlete performing a lateral lunge with hips shifted back and foot planted.'),
  },
] satisfies Exercise[];

export const expandedUpperBodyExercises = [
  {
    ...reviewMeta('low'),
    id: 'chest_supported_dumbbell_row',
    name: 'Chest-Supported Dumbbell Row',
    shortName: 'Supported DB Row',
    category: 'hypertrophy',
    summary: 'Bench-supported horizontal pull that biases upper back while reducing low-back demand.',
    coachingSummary: 'Let the bench support the trunk, pull elbows toward the back pockets, and pause without shrugging.',
    movementPatternIds: ['horizontal_pull'],
    subPatternIds: ['supported_row', 'scapular_retraction'],
    primaryMuscleIds: ['upper_back', 'lats'],
    secondaryMuscleIds: ['rear_delts', 'biceps', 'forearms'],
    jointsInvolved: ['shoulders', 'elbows', 'wrists'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['dumbbells', 'bench'],
    equipmentRequiredIds: ['dumbbells', 'bench'],
    equipmentOptionalIds: [],
    setupType: 'bench',
    workoutTypeIds: ['hypertrophy', 'upper_strength', 'strength'],
    goalIds: ['dumbbell_hypertrophy', 'upper_body_strength', 'full_gym_strength'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'moderate',
    fatigueCost: 'moderate',
    intensity: 'moderate',
    impact: 'none',
    spineLoading: 'low',
    kneeDemand: 'none',
    hipDemand: 'low',
    shoulderDemand: 'moderate',
    wristDemand: 'moderate',
    ankleDemand: 'none',
    balanceDemand: 'none',
    cardioDemand: 'low',
    spaceRequired: ['small_space'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['band_row', 'one_arm_dumbbell_row'],
    progressionExerciseIds: ['barbell_row', 'seated_cable_row'],
    substitutionExerciseIds: ['one_arm_dumbbell_row', 'seated_cable_row', 'band_row'],
    contraindicationFlags: ['shoulder_caution', 'wrist_caution'],
    setupInstructions: [
      'Set an incline bench high enough that the chest can rest without neck strain.',
      'Hold dumbbells under the shoulders and let the shoulder blades reach slightly at the bottom.',
    ],
    executionInstructions: [
      'Row the elbows toward the ribs or back pockets without lifting the chest off the bench.',
      'Pause briefly, then lower until the shoulder blades can move without losing control.',
    ],
    breathingInstructions: [
      'Exhale as the elbows travel back.',
      'Inhale as the dumbbells lower and the upper back resets.',
    ],
    safetyNotes: [
      'Use a neutral wrist and lighter load if wrist pressure builds.',
      'Stop before shoulder pinching or neck tension becomes the limiter.',
    ],
    trackingMetricIds: ['sets_completed', 'reps_completed', 'load_used', 'actual_rpe', 'movement_quality'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 4 },
      reps: { min: 8, max: 15 },
      rpe: { min: 6, max: 8 },
      restSeconds: { min: 60, max: 120 },
    },
    defaultPrescriptionTemplateId: 'hypertrophy_straight',
    media: pendingMedia('Athlete rowing dumbbells while chest-supported on an incline bench.'),
  },
  {
    ...reviewMeta('low'),
    id: 'cable_face_pull',
    name: 'Cable Face Pull',
    shortName: 'Face Pull',
    category: 'prehab',
    summary: 'Cable shoulder-support exercise for rear delts, upper back, and rotator cuff control.',
    coachingSummary: 'Pull toward eye level, keep ribs quiet, and finish with shoulder blades controlled rather than shrugged.',
    movementPatternIds: ['horizontal_pull', 'shoulder_prehab'],
    subPatternIds: ['scapular_retraction', 'external_rotation_bias'],
    primaryMuscleIds: ['rear_delts', 'rotator_cuff', 'upper_back'],
    secondaryMuscleIds: ['shoulders', 'biceps'],
    jointsInvolved: ['shoulders', 'elbows'],
    planeOfMotion: 'transverse',
    equipmentIds: ['cable_machine', 'resistance_band'],
    equipmentRequiredIds: ['cable_machine'],
    equipmentOptionalIds: ['resistance_band'],
    setupType: 'standing',
    workoutTypeIds: ['upper_strength', 'hypertrophy', 'boxing_support', 'mobility'],
    goalIds: ['upper_body_strength', 'dumbbell_hypertrophy', 'boxing_support', 'mobility'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'low',
    impact: 'none',
    spineLoading: 'none',
    kneeDemand: 'none',
    hipDemand: 'none',
    shoulderDemand: 'moderate',
    wristDemand: 'low',
    ankleDemand: 'none',
    balanceDemand: 'low',
    cardioDemand: 'none',
    spaceRequired: ['small_space'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['band_pull_apart', 'band_external_rotation'],
    progressionExerciseIds: ['seated_cable_row'],
    substitutionExerciseIds: ['band_pull_apart', 'band_external_rotation', 'wall_slide'],
    contraindicationFlags: ['shoulder_caution', 'no_overhead_pressing'],
    setupInstructions: [
      'Set the cable around face height and take a stance far enough back to keep steady tension.',
      'Start with arms long, ribs down, and shoulders away from the ears.',
    ],
    executionInstructions: [
      'Pull the rope toward the face while elbows travel wide and shoulder blades move back.',
      'Finish without leaning back, shrugging, or forcing extra range.',
    ],
    breathingInstructions: [
      'Exhale during the pull.',
      'Inhale while returning slowly to the start.',
    ],
    safetyNotes: [
      'Use band pull-aparts or wall slides if cable angle irritates the shoulder.',
      'Keep load light enough that neck tension does not take over.',
    ],
    trackingMetricIds: ['sets_completed', 'reps_completed', 'load_used', 'actual_rpe', 'movement_quality'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 3 },
      reps: { min: 12, max: 20 },
      rpe: { min: 4, max: 7 },
      restSeconds: { min: 30, max: 75 },
    },
    defaultPrescriptionTemplateId: 'shoulder_prehab',
    media: pendingMedia('Athlete performing a cable face pull with elbows wide and shoulders controlled.'),
  },
  {
    ...reviewMeta('low'),
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    shortName: 'Incline Curl',
    category: 'hypertrophy',
    summary: 'Bench-supported elbow-flexion accessory that loads biceps through a longer range.',
    coachingSummary: 'Keep upper arms quiet, curl without swinging, and stop before shoulder discomfort appears.',
    movementPatternIds: ['vertical_pull'],
    subPatternIds: ['elbow_flexion_accessory'],
    primaryMuscleIds: ['biceps'],
    secondaryMuscleIds: ['forearms', 'shoulders'],
    jointsInvolved: ['elbows', 'shoulders', 'wrists'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['dumbbells', 'bench'],
    equipmentRequiredIds: ['dumbbells', 'bench'],
    equipmentOptionalIds: [],
    setupType: 'bench',
    workoutTypeIds: ['hypertrophy', 'upper_strength'],
    goalIds: ['hypertrophy', 'dumbbell_hypertrophy', 'upper_body_strength'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'moderate',
    fatigueCost: 'low',
    intensity: 'moderate',
    impact: 'none',
    spineLoading: 'none',
    kneeDemand: 'none',
    hipDemand: 'none',
    shoulderDemand: 'low',
    wristDemand: 'moderate',
    ankleDemand: 'none',
    balanceDemand: 'none',
    cardioDemand: 'none',
    spaceRequired: ['small_space'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['dumbbell_curl'],
    progressionExerciseIds: [],
    substitutionExerciseIds: ['dumbbell_curl', 'band_row'],
    contraindicationFlags: ['wrist_caution', 'shoulder_caution'],
    setupInstructions: [
      'Set an incline bench low enough to feel a stretch without shoulder irritation.',
      'Hold dumbbells with arms hanging naturally and wrists neutral.',
    ],
    executionInstructions: [
      'Curl without letting the elbows drift forward or the shoulders roll.',
      'Lower slowly until the biceps are lengthened but the shoulder still feels comfortable.',
    ],
    breathingInstructions: [
      'Exhale as the dumbbells curl up.',
      'Inhale as they lower under control.',
    ],
    safetyNotes: [
      'Use a standard dumbbell curl if the shoulder feels pulled forward.',
      'Keep wrists neutral and reduce load if elbow or wrist discomfort appears.',
    ],
    trackingMetricIds: ['sets_completed', 'reps_completed', 'load_used', 'actual_rpe'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 4 },
      reps: { min: 10, max: 15 },
      rpe: { min: 6, max: 8 },
      restSeconds: { min: 45, max: 90 },
    },
    defaultPrescriptionTemplateId: 'accessory_volume',
    media: pendingMedia('Athlete performing an incline dumbbell curl with upper arms quiet and wrists neutral.'),
  },
] satisfies Exercise[];

export const expandedCoreExercises = [
  {
    ...reviewMeta('moderate'),
    id: 'hollow_body_hold',
    name: 'Hollow Body Hold',
    shortName: 'Hollow Hold',
    category: 'strength',
    summary: 'Anti-extension trunk hold that trains rib-pelvis control and anterior core endurance.',
    coachingSummary: 'Press the low back gently toward the floor and choose the lever length you can control while breathing.',
    movementPatternIds: ['anti_extension', 'trunk_flexion'],
    subPatternIds: ['isometric_trunk_control'],
    primaryMuscleIds: ['rectus_abs', 'transverse_abs'],
    secondaryMuscleIds: ['hip_flexors', 'core'],
    jointsInvolved: ['spine', 'hips'],
    planeOfMotion: 'static',
    equipmentIds: ['bodyweight', 'mat'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['mat'],
    setupType: 'floor',
    workoutTypeIds: ['core_durability', 'bodyweight_strength', 'strength'],
    goalIds: ['core_durability', 'no_equipment', 'beginner_strength'],
    minExperience: 'beginner',
    technicalComplexity: 'moderate',
    loadability: 'low',
    fatigueCost: 'moderate',
    intensity: 'moderate',
    impact: 'none',
    spineLoading: 'low',
    kneeDemand: 'none',
    hipDemand: 'moderate',
    shoulderDemand: 'low',
    wristDemand: 'none',
    ankleDemand: 'none',
    balanceDemand: 'none',
    cardioDemand: 'low',
    spaceRequired: ['mat'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['dead_bug'],
    progressionExerciseIds: ['front_plank'],
    substitutionExerciseIds: ['dead_bug', 'front_plank', 'bird_dog'],
    contraindicationFlags: ['back_caution', 'no_floor_work'],
    setupInstructions: [
      'Lie on the back and bring ribs and pelvis into a stacked position.',
      'Start with knees bent if a long lever pulls the low back away from the floor.',
    ],
    executionInstructions: [
      'Hold the chosen shape while keeping breathing quiet and the low back controlled.',
      'End the set before the neck, hip flexors, or low back take over.',
    ],
    breathingInstructions: [
      'Use short steady exhales while keeping the trunk position.',
      'Regress lever length if breathing becomes braced or held.',
    ],
    safetyNotes: [
      'Use dead bug if low-back pressure rises or breathing cannot stay controlled.',
      'Avoid this variation when no-floor-work constraints are active.',
    ],
    trackingMetricIds: ['duration_minutes', 'movement_quality', 'breathing_quality', 'actual_rpe'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 4 },
      holdSeconds: { min: 10, max: 30 },
      rpe: { min: 5, max: 7 },
      restSeconds: { min: 30, max: 60 },
    },
    defaultPrescriptionTemplateId: 'core_control',
    media: pendingMedia('Athlete holding a hollow body position with controlled ribs and pelvis.'),
  },
  {
    ...reviewMeta('moderate'),
    id: 'copenhagen_side_plank_short_lever',
    name: 'Short-Lever Copenhagen Side Plank',
    shortName: 'Copenhagen Plank',
    category: 'strength',
    summary: 'Adductor and lateral-trunk durability drill using a short lever for controlled exposure.',
    coachingSummary: 'Use the knee-supported version first, stack the ribs and pelvis, and stop before groin strain.',
    movementPatternIds: ['anti_rotation', 'balance'],
    subPatternIds: ['lateral_trunk_hold', 'adductor_isometric'],
    primaryMuscleIds: ['adductors', 'obliques'],
    secondaryMuscleIds: ['glutes', 'core', 'shoulders'],
    jointsInvolved: ['hips', 'spine', 'shoulders'],
    planeOfMotion: 'frontal',
    equipmentIds: ['bodyweight', 'bench', 'mat'],
    equipmentRequiredIds: ['bodyweight', 'bench'],
    equipmentOptionalIds: ['mat'],
    setupType: 'floor',
    workoutTypeIds: ['core_durability', 'strength', 'boxing_support'],
    goalIds: ['core_durability', 'lower_body_strength', 'boxing_support'],
    minExperience: 'intermediate',
    technicalComplexity: 'moderate',
    loadability: 'low',
    fatigueCost: 'moderate',
    intensity: 'moderate',
    impact: 'none',
    spineLoading: 'low',
    kneeDemand: 'low',
    hipDemand: 'high',
    shoulderDemand: 'moderate',
    wristDemand: 'low',
    ankleDemand: 'none',
    balanceDemand: 'moderate',
    cardioDemand: 'low',
    spaceRequired: ['mat', 'small_space'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: false,
    regressionExerciseIds: ['side_plank', 'glute_bridge'],
    progressionExerciseIds: ['lateral_lunge'],
    substitutionExerciseIds: ['side_plank', 'pallof_press', 'lateral_lunge'],
    contraindicationFlags: ['no_floor_work', 'shoulder_caution', 'knee_caution'],
    setupInstructions: [
      'Place the top knee on a bench and set the lower elbow under the shoulder.',
      'Stack ribs over pelvis and keep the bottom leg bent for the short-lever version.',
    ],
    executionInstructions: [
      'Lift into a side plank and lightly press the top knee into the bench.',
      'Hold until position or breathing quality begins to fade, then lower with control.',
    ],
    breathingInstructions: [
      'Breathe steadily behind the brace.',
      'Stop the hold if breathing becomes strained or the shoulder collapses.',
    ],
    safetyNotes: [
      'Regress to side plank if groin, knee, or shoulder discomfort appears.',
      'Do not use as a fatigue finisher after heavy adductor or lateral-lunge work.',
    ],
    trackingMetricIds: ['duration_minutes', 'movement_quality', 'pain_score_after', 'actual_rpe'],
    defaultPrescriptionRanges: {
      sets: { min: 2, max: 3 },
      holdSeconds: { min: 10, max: 25, unit: 'per_side' },
      rpe: { min: 5, max: 7 },
      restSeconds: { min: 45, max: 90 },
    },
    defaultPrescriptionTemplateId: 'core_control',
    media: pendingMedia('Athlete performing a short-lever Copenhagen side plank with top knee supported.'),
  },
] satisfies Exercise[];

export const expandedCardioExercises = [
  {
    ...reviewMeta('low'),
    id: 'elliptical_zone2',
    name: 'Elliptical Zone 2',
    shortName: 'Elliptical Z2',
    category: 'cardio',
    summary: 'Low-impact steady aerobic work using an elliptical trainer.',
    coachingSummary: 'Keep posture tall, cadence smooth, and effort conversational from start to finish.',
    movementPatternIds: ['locomotion'],
    subPatternIds: ['elliptical_cyclic_cardio', 'low_impact_aerobic'],
    primaryMuscleIds: ['aerobic_system'],
    secondaryMuscleIds: ['quads', 'glutes', 'calves'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['elliptical'],
    equipmentRequiredIds: ['elliptical'],
    equipmentOptionalIds: [],
    setupType: 'machine',
    workoutTypeIds: ['zone2_cardio', 'recovery', 'low_impact_conditioning'],
    goalIds: ['zone2_cardio', 'recovery', 'low_impact_conditioning'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'low',
    impact: 'low',
    spineLoading: 'none',
    kneeDemand: 'low',
    hipDemand: 'low',
    shoulderDemand: 'low',
    wristDemand: 'low',
    ankleDemand: 'low',
    balanceDemand: 'low',
    cardioDemand: 'moderate',
    spaceRequired: ['machine_station'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['easy_walk', 'stationary_bike_zone2'],
    progressionExerciseIds: ['incline_walk', 'rower_zone2'],
    substitutionExerciseIds: ['stationary_bike_zone2', 'incline_walk', 'rower_zone2'],
    contraindicationFlags: [],
    setupInstructions: [
      'Set resistance low enough that cadence stays smooth and posture stays tall.',
      'Use handrails lightly if balance or confidence needs support.',
    ],
    executionInstructions: [
      'Move continuously at a conversational effort.',
      'Adjust resistance before cadence breaks or breathing becomes strained.',
    ],
    breathingInstructions: [
      'Use nasal or relaxed mouth breathing when possible.',
      'You should be able to speak in short sentences without gasping.',
    ],
    safetyNotes: [
      'Step off and choose bike or walking if dizziness or joint discomfort appears.',
      'Avoid turning the session into intervals when the intent is Zone 2.',
    ],
    trackingMetricIds: ['duration_minutes', 'heart_rate_zone', 'heart_rate_avg', 'actual_rpe', 'calories_optional'],
    defaultPrescriptionRanges: {
      durationMinutes: { min: 20, max: 45 },
      rpe: { min: 2, max: 4 },
      heartRateZone: { min: 2, max: 2, unit: 'zone' },
      talkTest: 'conversational',
    },
    defaultPrescriptionTemplateId: 'zone2_steady',
    media: pendingMedia('Athlete using an elliptical with tall posture and smooth low-impact cadence.'),
  },
  {
    ...reviewMeta('low'),
    id: 'swim_easy_zone2',
    name: 'Easy Swim Zone 2',
    shortName: 'Easy Swim',
    category: 'cardio',
    summary: 'Pool-based easy aerobic session for low-impact conditioning and recovery support.',
    coachingSummary: 'Swim at a pace that keeps breathing controlled and stroke rhythm relaxed.',
    movementPatternIds: ['locomotion'],
    subPatternIds: ['pool_aerobic', 'low_impact_aerobic'],
    primaryMuscleIds: ['aerobic_system'],
    secondaryMuscleIds: ['lats', 'shoulders', 'core', 'glutes'],
    jointsInvolved: ['shoulders', 'spine', 'hips', 'knees', 'ankles'],
    planeOfMotion: 'multi_planar',
    equipmentIds: ['pool'],
    equipmentRequiredIds: ['pool'],
    equipmentOptionalIds: [],
    setupType: 'locomotion',
    workoutTypeIds: ['zone2_cardio', 'recovery', 'low_impact_conditioning'],
    goalIds: ['zone2_cardio', 'recovery', 'low_impact_conditioning'],
    minExperience: 'beginner',
    technicalComplexity: 'moderate',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'low',
    impact: 'none',
    spineLoading: 'none',
    kneeDemand: 'low',
    hipDemand: 'low',
    shoulderDemand: 'moderate',
    wristDemand: 'low',
    ankleDemand: 'low',
    balanceDemand: 'none',
    cardioDemand: 'moderate',
    spaceRequired: ['machine_station'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['easy_walk', 'stationary_bike_zone2'],
    progressionExerciseIds: ['rower_zone2'],
    substitutionExerciseIds: ['stationary_bike_zone2', 'elliptical_zone2', 'easy_walk'],
    contraindicationFlags: ['shoulder_caution'],
    setupInstructions: [
      'Choose a lane or pool space where pace can stay relaxed and uninterrupted.',
      'Use the stroke that keeps breathing controlled and shoulders comfortable.',
    ],
    executionInstructions: [
      'Swim continuously or in relaxed repeats while staying conversational by effort.',
      'Rest briefly if stroke mechanics or breathing rhythm deteriorates.',
    ],
    breathingInstructions: [
      'Keep exhale steady in the water and inhale without rushing the stroke.',
      'Reduce pace if breathing becomes panicked or forced.',
    ],
    safetyNotes: [
      'Use a non-swim modality if shoulder symptoms or breathing control worsens.',
      'Pool work requires normal water-safety judgment and appropriate supervision when needed.',
    ],
    trackingMetricIds: ['duration_minutes', 'distance', 'actual_rpe', 'breathing_quality', 'notes'],
    defaultPrescriptionRanges: {
      durationMinutes: { min: 15, max: 35 },
      rpe: { min: 2, max: 4 },
      talkTest: 'relaxed breathing between lengths',
    },
    defaultPrescriptionTemplateId: 'zone2_steady',
    media: pendingMedia('Athlete swimming at an easy aerobic pace with relaxed stroke rhythm.'),
  },
  {
    ...reviewMeta('moderate'),
    id: 'assault_bike_intervals',
    name: 'Assault Bike Intervals',
    shortName: 'Bike Intervals',
    category: 'conditioning',
    summary: 'Low-impact fan-bike intervals for repeatable conditioning without running or jumping.',
    coachingSummary: 'Push each interval hard but repeatable, then recover enough to keep the next round clean.',
    movementPatternIds: ['locomotion'],
    subPatternIds: ['fan_bike_intervals', 'low_impact_hiit'],
    primaryMuscleIds: ['aerobic_system', 'full_body'],
    secondaryMuscleIds: ['quads', 'glutes', 'shoulders', 'lats'],
    jointsInvolved: ['hips', 'knees', 'ankles', 'shoulders', 'elbows'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['assault_bike'],
    equipmentRequiredIds: ['assault_bike'],
    equipmentOptionalIds: [],
    setupType: 'machine',
    workoutTypeIds: ['conditioning', 'low_impact_conditioning'],
    goalIds: ['low_impact_conditioning', 'boxing_support'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'moderate',
    fatigueCost: 'high',
    intensity: 'hard',
    impact: 'low',
    spineLoading: 'none',
    kneeDemand: 'moderate',
    hipDemand: 'moderate',
    shoulderDemand: 'moderate',
    wristDemand: 'low',
    ankleDemand: 'low',
    balanceDemand: 'none',
    cardioDemand: 'high',
    spaceRequired: ['machine_station'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['stationary_bike_zone2', 'elliptical_zone2'],
    progressionExerciseIds: ['sled_push', 'battle_rope_wave'],
    substitutionExerciseIds: ['sled_push', 'battle_rope_wave', 'rower_zone2'],
    contraindicationFlags: ['poor_readiness', 'high_fatigue', 'illness_caution'],
    setupInstructions: [
      'Set seat height so knees stay slightly bent at the bottom of the pedal stroke.',
      'Start with an easy ramp before the first hard interval.',
    ],
    executionInstructions: [
      'Drive arms and legs together during work intervals without rounding or rocking excessively.',
      'Use the full rest interval so output remains repeatable.',
    ],
    breathingInstructions: [
      'Breathe rhythmically during work and focus on slowing exhale during rest.',
      'Do not start the next round until breathing is controlled enough to repeat quality.',
    ],
    safetyNotes: [
      'Switch to Zone 2 or recovery work when readiness is red, illness is active, or breathing feels unusual.',
      'Stop the interval set if output collapses or symptoms change.',
    ],
    trackingMetricIds: ['rounds_completed', 'work_seconds', 'rest_seconds', 'actual_rpe', 'breathing_quality'],
    defaultPrescriptionRanges: {
      rounds: { min: 4, max: 8 },
      workSeconds: { min: 20, max: 45 },
      restIntervalSeconds: { min: 60, max: 120 },
      rpe: { min: 7, max: 9 },
    },
    defaultPrescriptionTemplateId: 'conditioning_interval',
    media: pendingMedia('Athlete performing repeatable low-impact intervals on an assault bike.'),
  },
] satisfies Exercise[];

export const expandedMobilityExercises = [
  {
    ...reviewMeta('low'),
    id: 'couch_stretch',
    name: 'Couch Stretch',
    shortName: 'Couch Stretch',
    category: 'flexibility',
    summary: 'Hip-flexor and quad flexibility drill using a wall, bench, or couch support.',
    coachingSummary: 'Stack ribs over pelvis, squeeze the back glute lightly, and use a range that stays calm.',
    movementPatternIds: ['hip_mobility'],
    subPatternIds: ['hip_flexor_length', 'quad_flexibility'],
    primaryMuscleIds: ['hip_flexors', 'quads'],
    secondaryMuscleIds: ['glutes', 'core'],
    jointsInvolved: ['hips', 'knees', 'spine'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['bodyweight', 'bench', 'mat'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['bench', 'mat'],
    setupType: 'floor',
    workoutTypeIds: ['mobility', 'recovery'],
    goalIds: ['mobility', 'recovery', 'return_to_training'],
    minExperience: 'beginner',
    technicalComplexity: 'moderate',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'low',
    impact: 'none',
    spineLoading: 'none',
    kneeDemand: 'moderate',
    hipDemand: 'moderate',
    shoulderDemand: 'none',
    wristDemand: 'none',
    ankleDemand: 'low',
    balanceDemand: 'low',
    cardioDemand: 'none',
    spaceRequired: ['mat', 'small_space'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['half_kneeling_hip_flexor'],
    progressionExerciseIds: ['worlds_greatest_stretch'],
    substitutionExerciseIds: ['half_kneeling_hip_flexor', 'worlds_greatest_stretch'],
    contraindicationFlags: ['knee_caution'],
    setupInstructions: [
      'Place the back knee on padding and the back foot against a wall, bench, or couch only as high as comfortable.',
      'Bring the torso tall and gently tuck the pelvis without forcing the low back.',
    ],
    executionInstructions: [
      'Hold the position with the back glute lightly active and ribs stacked over pelvis.',
      'Reduce foot height or move farther from the wall if knee pressure or quad pull is too strong.',
    ],
    breathingInstructions: [
      'Use slow exhales to soften the stretch.',
      'Avoid holding the breath or forcing depth.',
    ],
    safetyNotes: [
      'Regress to half-kneeling hip flexor stretch if knee pressure appears.',
      'This should feel like a mild stretch, not a joint pinch.',
    ],
    trackingMetricIds: ['range_quality', 'breathing_quality', 'symptom_change', 'duration_minutes'],
    defaultPrescriptionRanges: {
      holdSeconds: { min: 30, max: 60, unit: 'per_side' },
      targetJoints: ['hips', 'knees'],
      targetTissues: ['hip_flexors', 'quads'],
      rangeOfMotionIntent: 'Relax hip flexor and quad tension while keeping pelvis controlled.',
    },
    defaultPrescriptionTemplateId: 'flexibility_hold',
    media: pendingMedia('Athlete performing a couch stretch with back knee padded and torso stacked.'),
  },
  {
    ...reviewMeta('low'),
    id: 'doorway_pec_stretch',
    name: 'Doorway Pec Stretch',
    shortName: 'Doorway Pec',
    category: 'flexibility',
    summary: 'Chest and anterior-shoulder stretch for upper-body recovery and posture support.',
    coachingSummary: 'Set the forearm on the door frame, step through gently, and keep shoulder sensation mild.',
    movementPatternIds: ['shoulder_prehab'],
    subPatternIds: ['pec_flexibility', 'anterior_shoulder_opener'],
    primaryMuscleIds: ['chest'],
    secondaryMuscleIds: ['shoulders', 'biceps'],
    jointsInvolved: ['shoulders', 'elbows', 'spine'],
    planeOfMotion: 'transverse',
    equipmentIds: ['bodyweight'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: [],
    setupType: 'standing',
    workoutTypeIds: ['mobility', 'recovery', 'upper_strength'],
    goalIds: ['mobility', 'recovery', 'upper_body_strength', 'boxing_support'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'low',
    impact: 'none',
    spineLoading: 'none',
    kneeDemand: 'none',
    hipDemand: 'none',
    shoulderDemand: 'moderate',
    wristDemand: 'low',
    ankleDemand: 'none',
    balanceDemand: 'low',
    cardioDemand: 'none',
    spaceRequired: ['small_space'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['wall_slide', 'band_pull_apart'],
    progressionExerciseIds: ['band_external_rotation'],
    substitutionExerciseIds: ['wall_slide', 'band_pull_apart', 'band_external_rotation'],
    contraindicationFlags: ['shoulder_caution'],
    setupInstructions: [
      'Place forearm or hand on a door frame below shoulder height at first.',
      'Stand tall and step through only until a mild chest stretch appears.',
    ],
    executionInstructions: [
      'Hold without twisting the trunk or letting the shoulder glide forward aggressively.',
      'Change arm height to find the most comfortable stretch line.',
    ],
    breathingInstructions: [
      'Use slow exhales to keep the shoulder relaxed.',
      'Back out of the range if breathing becomes braced.',
    ],
    safetyNotes: [
      'Avoid aggressive shoulder angles when shoulder caution or pain is active.',
      'Use wall slides instead if the stretch creates numbness, tingling, or pinching.',
    ],
    trackingMetricIds: ['range_quality', 'symptom_change', 'breathing_quality'],
    defaultPrescriptionRanges: {
      holdSeconds: { min: 20, max: 45, unit: 'per_side' },
      targetJoints: ['shoulders'],
      targetTissues: ['chest', 'anterior_shoulders'],
      rangeOfMotionIntent: 'Reduce anterior shoulder and chest stiffness without forcing range.',
    },
    defaultPrescriptionTemplateId: 'flexibility_hold',
    media: pendingMedia('Athlete using a doorway for a mild pec stretch with shoulder below aggressive range.'),
  },
] satisfies Exercise[];

export const expandedRecoveryExercises = [
  {
    ...reviewMeta('low'),
    id: 'tandem_walk',
    name: 'Tandem Walk',
    shortName: 'Tandem Walk',
    category: 'balance',
    summary: 'Supported heel-to-toe walking drill for balance confidence and gait control.',
    coachingSummary: 'Move slowly near support, keep eyes forward, and prioritize calm control over distance.',
    movementPatternIds: ['balance', 'locomotion'],
    subPatternIds: ['narrow_base_gait', 'dynamic_balance'],
    primaryMuscleIds: ['feet_intrinsics', 'calves', 'core'],
    secondaryMuscleIds: ['glutes', 'quads'],
    jointsInvolved: ['ankles', 'hips', 'knees', 'spine'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['bodyweight', 'open_space'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['open_space'],
    setupType: 'standing',
    workoutTypeIds: ['mobility', 'recovery', 'core_durability'],
    goalIds: ['mobility', 'recovery', 'core_durability', 'return_to_training'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'low',
    impact: 'low',
    spineLoading: 'none',
    kneeDemand: 'low',
    hipDemand: 'low',
    shoulderDemand: 'none',
    wristDemand: 'none',
    ankleDemand: 'moderate',
    balanceDemand: 'high',
    cardioDemand: 'low',
    spaceRequired: ['small_space'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['single_leg_balance'],
    progressionExerciseIds: ['step_up'],
    substitutionExerciseIds: ['single_leg_balance', 'easy_walk'],
    contraindicationFlags: ['severe_dizziness', 'fainting'],
    setupInstructions: [
      'Stand near a wall, rail, or stable counter before starting.',
      'Set eyes forward and choose a short lane with no trip hazards.',
    ],
    executionInstructions: [
      'Walk heel-to-toe slowly, using support as needed before balance becomes rushed.',
      'Turn around only after regaining a stable two-foot stance.',
    ],
    breathingInstructions: [
      'Keep breathing slow and steady.',
      'Pause if breath holding or rushing appears.',
    ],
    safetyNotes: [
      'Use hand support and stop before dizziness, stumbles, or fear take over.',
      'Do not progress balance complexity after fainting, severe dizziness, or acute neurological symptoms.',
    ],
    trackingMetricIds: ['movement_quality', 'breathing_quality', 'symptom_change', 'completion_status'],
    defaultPrescriptionRanges: {
      durationSeconds: { min: 20, max: 60 },
      reps: { min: 2, max: 4, unit: 'passes' },
      rpe: { min: 1, max: 4 },
    },
    defaultPrescriptionTemplateId: 'core_control',
    media: pendingMedia('Athlete performing slow heel-to-toe tandem walking near stable support.'),
  },
  {
    ...reviewMeta('low'),
    id: 'legs_up_breathing',
    name: 'Legs-Up Breathing',
    shortName: 'Legs-Up Breathing',
    category: 'recovery',
    summary: 'Low-stress breathing reset with legs supported to downshift after hard training or high fatigue.',
    coachingSummary: 'Support the legs, relax the jaw and shoulders, and let exhales slow the session down.',
    movementPatternIds: ['breathing'],
    subPatternIds: ['downregulation', 'supported_recovery'],
    primaryMuscleIds: ['diaphragm'],
    secondaryMuscleIds: ['core', 'calves'],
    jointsInvolved: ['hips', 'spine'],
    planeOfMotion: 'static',
    equipmentIds: ['bodyweight', 'mat', 'bench'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['mat', 'bench'],
    setupType: 'floor',
    workoutTypeIds: ['recovery', 'mobility'],
    goalIds: ['recovery', 'return_to_training', 'mobility'],
    minExperience: 'beginner',
    technicalComplexity: 'low',
    loadability: 'low',
    fatigueCost: 'low',
    intensity: 'recovery',
    impact: 'none',
    spineLoading: 'none',
    kneeDemand: 'none',
    hipDemand: 'low',
    shoulderDemand: 'none',
    wristDemand: 'none',
    ankleDemand: 'none',
    balanceDemand: 'none',
    cardioDemand: 'low',
    spaceRequired: ['mat'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['crocodile_breathing', 'childs_pose_breathing'],
    progressionExerciseIds: ['easy_walk'],
    substitutionExerciseIds: ['crocodile_breathing', 'childs_pose_breathing', 'easy_walk'],
    contraindicationFlags: ['no_floor_work'],
    setupInstructions: [
      'Lie on the back with calves supported on a bench, couch, or wall.',
      'Set the head and shoulders comfortably so the neck can relax.',
    ],
    executionInstructions: [
      'Let the ribs soften and keep the breath quiet for the prescribed duration.',
      'End by rolling to the side and sitting up slowly.',
    ],
    breathingInstructions: [
      'Inhale gently through the nose if comfortable.',
      'Use longer, unforced exhales to settle breathing.',
    ],
    safetyNotes: [
      'Use seated breathing if getting to the floor is not appropriate.',
      'Stop and sit up if dizziness, discomfort, or anxiety increases.',
    ],
    trackingMetricIds: ['duration_minutes', 'breathing_quality', 'readiness_after', 'symptom_change'],
    defaultPrescriptionRanges: {
      durationMinutes: { min: 3, max: 8 },
      rpe: { min: 1, max: 2 },
      talkTest: 'breathing should feel calm and unforced',
    },
    defaultPrescriptionTemplateId: 'breathing_reset',
    media: pendingMedia('Athlete lying on back with legs supported while practicing calm breathing.'),
  },
] satisfies Exercise[];

export const expandedPowerExercises = [
  {
    ...reviewMeta('moderate'),
    id: 'med_ball_chest_pass',
    name: 'Medicine Ball Chest Pass',
    shortName: 'MB Chest Pass',
    category: 'power',
    summary: 'Explosive horizontal push drill for upper-body power and trunk stiffness.',
    coachingSummary: 'Throw fast from a braced stance, reset fully, and stop before speed drops.',
    movementPatternIds: ['horizontal_push'],
    subPatternIds: ['upper_body_throw', 'boxing_power_support'],
    primaryMuscleIds: ['chest', 'triceps', 'shoulders'],
    secondaryMuscleIds: ['core', 'glutes'],
    jointsInvolved: ['shoulders', 'elbows', 'wrists', 'spine', 'hips'],
    planeOfMotion: 'sagittal',
    equipmentIds: ['medicine_ball', 'open_space'],
    equipmentRequiredIds: ['medicine_ball', 'open_space'],
    equipmentOptionalIds: [],
    setupType: 'standing',
    workoutTypeIds: ['power', 'boxing_support', 'upper_strength'],
    goalIds: ['boxing_support', 'upper_body_strength', 'full_gym_strength'],
    minExperience: 'intermediate',
    technicalComplexity: 'moderate',
    loadability: 'moderate',
    fatigueCost: 'moderate',
    intensity: 'hard',
    impact: 'low',
    spineLoading: 'low',
    kneeDemand: 'low',
    hipDemand: 'moderate',
    shoulderDemand: 'high',
    wristDemand: 'moderate',
    ankleDemand: 'low',
    balanceDemand: 'moderate',
    cardioDemand: 'low',
    spaceRequired: ['open_space'],
    homeFriendly: false,
    gymFriendly: true,
    beginnerFriendly: false,
    regressionExerciseIds: ['push_up', 'incline_push_up'],
    progressionExerciseIds: ['med_ball_rotational_throw'],
    substitutionExerciseIds: ['medicine_ball_slam', 'landmine_press', 'push_up'],
    contraindicationFlags: ['shoulder_caution', 'wrist_caution'],
    setupInstructions: [
      'Use a light medicine ball and a wall or partner setup that allows a safe catch or rebound.',
      'Stand tall with ribs stacked and feet rooted before each throw.',
    ],
    executionInstructions: [
      'Throw from the chest with maximal speed and a crisp finish.',
      'Reset fully between reps instead of turning the drill into conditioning.',
    ],
    breathingInstructions: [
      'Inhale and brace before the throw.',
      'Exhale sharply through the throw, then recover before the next rep.',
    ],
    safetyNotes: [
      'Skip if shoulder or wrist symptoms change during the catch or release.',
      'Keep reps low and stop when speed, aim, or trunk position fades.',
    ],
    trackingMetricIds: ['sets_completed', 'reps_completed', 'movement_quality', 'rest_seconds', 'actual_rpe'],
    defaultPrescriptionRanges: {
      sets: { min: 3, max: 5 },
      reps: { min: 3, max: 6 },
      rpe: { min: 5, max: 7 },
      restSeconds: { min: 90, max: 180 },
    },
    defaultPrescriptionTemplateId: 'power_quality',
    media: pendingMedia('Athlete performing a fast medicine ball chest pass from a braced standing stance.'),
  },
  {
    ...reviewMeta('moderate'),
    id: 'shadow_boxing_footwork',
    name: 'Shadow Boxing Footwork',
    shortName: 'Shadow Footwork',
    category: 'skill',
    summary: 'Low-contact boxing-support drill for rhythm, stance control, trunk rotation, and footwork.',
    coachingSummary: 'Move lightly, keep stance organized, and treat this as skill support rather than sparring.',
    movementPatternIds: ['locomotion', 'rotation'],
    subPatternIds: ['boxing_footwork', 'skill_conditioning'],
    primaryMuscleIds: ['aerobic_system', 'calves', 'core'],
    secondaryMuscleIds: ['shoulders', 'glutes', 'obliques'],
    jointsInvolved: ['ankles', 'knees', 'hips', 'spine', 'shoulders'],
    planeOfMotion: 'multi_planar',
    equipmentIds: ['bodyweight', 'open_space'],
    equipmentRequiredIds: ['bodyweight'],
    equipmentOptionalIds: ['open_space'],
    setupType: 'standing',
    workoutTypeIds: ['boxing_support', 'conditioning', 'low_impact_conditioning'],
    goalIds: ['boxing_support', 'low_impact_conditioning', 'return_to_training'],
    minExperience: 'beginner',
    technicalComplexity: 'moderate',
    loadability: 'low',
    fatigueCost: 'moderate',
    intensity: 'moderate',
    impact: 'low',
    spineLoading: 'none',
    kneeDemand: 'moderate',
    hipDemand: 'moderate',
    shoulderDemand: 'moderate',
    wristDemand: 'low',
    ankleDemand: 'moderate',
    balanceDemand: 'moderate',
    cardioDemand: 'moderate',
    spaceRequired: ['open_space'],
    homeFriendly: true,
    gymFriendly: true,
    beginnerFriendly: true,
    regressionExerciseIds: ['easy_walk', 'tandem_walk'],
    progressionExerciseIds: ['jump_rope_easy', 'battle_rope_wave'],
    substitutionExerciseIds: ['easy_walk', 'jump_rope_easy', 'battle_rope_wave'],
    contraindicationFlags: ['no_jumping', 'limited_space', 'knee_caution', 'high_fatigue'],
    setupInstructions: [
      'Clear enough space for small steps in every direction and begin in a comfortable stance.',
      'Choose a simple rhythm or combination that does not require maximal speed.',
    ],
    executionInstructions: [
      'Move in short rounds with stance, guard, and breathing organized.',
      'Keep contacts light and stop before footwork becomes sloppy or rushed.',
    ],
    breathingInstructions: [
      'Exhale lightly with punches or directional changes.',
      'Use the rest interval to bring breathing back under control.',
    ],
    safetyNotes: [
      'Keep this non-contact and low impact when used as generated support work.',
      'Reduce speed or switch to easy walking if knee, ankle, or dizziness signals appear.',
    ],
    trackingMetricIds: ['rounds_completed', 'duration_minutes', 'actual_rpe', 'movement_quality', 'breathing_quality'],
    defaultPrescriptionRanges: {
      rounds: { min: 3, max: 6 },
      durationSeconds: { min: 60, max: 180, unit: 'per_round' },
      restSeconds: { min: 45, max: 90 },
      rpe: { min: 4, max: 7 },
    },
    defaultPrescriptionTemplateId: 'conditioning_interval',
    media: pendingMedia('Athlete shadow boxing with light footwork, organized stance, and no contact.'),
  },
] satisfies Exercise[];
