export { calculateACWR } from './calculateACWR';
export { getHydrationProtocol } from './getHydrationProtocol';
export { adjustForBiology } from './adjustForBiology';
export { getGlobalReadinessState } from './getGlobalReadinessState';
export { handleTimelineShift, autoRegulateSC } from './adaptive';
export { calculateNutritionTargets, computeMacroAdherence, resolveDailyNutritionTargets } from './calculateNutrition';
export { calculateWeightTrend, calculateWeightCorrection, calculateWeightReadinessPenalty } from './calculateWeight';
export { calculateCampRisk } from './calculateCampRisk';
export { buildDailyMission, buildMicrocyclePlan } from './calculateMission';
export {
  determineFocus,
  scoreExerciseForUser,
  generateWorkout,
  generateWorkoutV2,
  calculateVolumeLoad,
  calculateWeeklyVolume,
  getWorkoutCompliance,
} from './calculateSC';
export {
  getRecoveryWindow,
  validateDayLoad,
  suggestAlternative,
  adjustNutritionForDay,
  detectOvertrainingRisk,
  generateWeekPlan,
  calculateWeeklyCompliance,
  getTrainingStreak,
} from './calculateSchedule';

export type {
  ACWRInput,
  ACWRResult,
  GlobalReadinessInput,
  ReadinessState,
  HydrationInput,
  HydrationResult,
  BiologyInput,
  BiologyResult,
  CyclePhase,
  Phase,
  FightStatus,
  TrainingSessionRow,
  ExerciseType,
  BlockType,
  TimelineStatus,
  MuscleGroup,
  Equipment,
  WorkoutType,
  WorkoutFocus,
  ExerciseLibraryRow,
  DailyTimelineRow,
  MacroLedgerRow,
  WorkoutPrescription,
  PrescribedExercise,
  ExerciseScoringContext,
  GenerateWorkoutInput,
  WorkoutLogRow,
  WorkoutSetLogRow,
  WorkoutComplianceResult,
  HandleTimelineShiftInput,
  HandleTimelineShiftResult,
  AutoRegulateSCInput,
  AutoRegulateSCResult,
  NutritionGoal,
  ActivityLevel,
  MealType,
  NutritionProfileInput,
  NutritionTargets,
  ResolvedNutritionTargets,
  MacroAdherenceResult,
  FoodItemRow,
  FoodLogRow,
  DailyNutritionSummaryRow,
  ActivityType,
  ComponentType,
  ScheduleSource,
  ScheduleStatus,
  SessionComponent,
  RecurringActivityRow,
  ScheduledActivityRow,
  ActivityLogEntry,
  WeeklyTargetsRow,
  DayLoadValidation,
  OvertrainingSeverity,
  OvertrainingWarning,
  WeeklyComplianceReport,
  ScheduleGenerationInput,
  NutritionDayAdjustment,
  WeeklyPlanEntryRow,
  WeightCutStatus,
  WeightDataPoint,
  WeightTrendInput,
  WeightTrendResult,
  WeightCorrectionInput,
  WeightCorrectionResult,
  WeightReadinessPenalty,
  RecurrencePattern,
  PerformanceObjective,
  MacrocycleContext,
  DailyMission,
  TrainingDirective,
  FuelDirective,
  HydrationDirective,
  RecoveryDirective,
  MissionRiskState,
  DecisionTraceItem,
  MissionOverride,
  WeeklyMissionPlan,
} from './types';

export type { CampRiskInput, CampRiskAssessment, CampRiskLevel } from './calculateCampRisk';


