import { StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, SPACING, RADIUS, SHADOWS } from '../theme/theme';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: 'transparent' },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.border,
    },
    headerTitle: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        letterSpacing: 1,
    },
    timer: {
        fontSize: 32,
        fontFamily: FONT_FAMILY.black,
        letterSpacing: -1,
    },
    pauseButton: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.borderLight,
        borderRadius: RADIUS.md,
    },
    pauseText: { fontSize: 18 },
    restTimerBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.sm + 2,
    },
    restTimerText: {
        fontSize: 15,
        fontFamily: FONT_FAMILY.semiBold,
        color: '#F5F5F0',
    },
    restSkipText: {
        fontSize: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: '#F5F5F099',
    },
    content: { padding: SPACING.lg },
    exerciseTitle: {
        fontSize: 16,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
    },
    exerciseMeta: {
        fontSize: 12,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.tertiary,
        marginBottom: SPACING.sm,
        textTransform: 'capitalize',
    },
    setHeader: {
        flexDirection: 'row',
        paddingBottom: SPACING.xs,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.borderLight,
    },
    setHeaderText: {
        flex: 1,
        fontSize: 10,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        textTransform: 'uppercase',
        textAlign: 'center',
    },
    setRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: SPACING.xs + 2,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.borderLight,
    },
    setNumber: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        textAlign: 'center',
    },
    setInput: {
        flex: 1,
        fontSize: 15,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
        textAlign: 'center',
        paddingVertical: SPACING.xs,
    },
    warmupToggle: {
        width: 18,
        height: 18,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: COLORS.border,
    },
    addSetButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.xs,
        paddingVertical: SPACING.sm + 2,
        marginTop: SPACING.xs,
    },
    addSetText: {
        fontSize: 13,
        fontFamily: FONT_FAMILY.semiBold,
    },
    addExerciseButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.sm,
        paddingVertical: SPACING.md + 2,
        borderRadius: RADIUS.lg,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        borderStyle: 'dashed',
        marginTop: SPACING.md,
    },
    addExerciseText: {
        fontSize: 15,
        fontFamily: FONT_FAMILY.semiBold,
    },
    quickAddTitle: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        marginBottom: SPACING.sm,
    },
    quickAddItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: SPACING.sm + 2,
        paddingHorizontal: SPACING.md,
        backgroundColor: COLORS.surface,
        borderRadius: RADIUS.md,
        marginBottom: SPACING.xs,
        ...SHADOWS.card,
    },
    quickAddName: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    quickAddMeta: {
        fontSize: 11,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.tertiary,
        textTransform: 'capitalize',
    },
    finishSection: {
        marginTop: SPACING.xl,
        alignItems: 'center',
        gap: SPACING.md,
    },
    finishLabel: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    rpeInput: {
        width: 80,
        fontSize: 24,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.text.primary,
        textAlign: 'center',
        borderWidth: 2,
        borderColor: COLORS.border,
        borderRadius: RADIUS.md,
        paddingVertical: SPACING.sm,
    },
    finishButtonWrapper: {
        marginTop: SPACING.xl,
        borderRadius: RADIUS.lg,
        overflow: 'hidden',
        ...SHADOWS.colored.accent,
    },
    finishButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.sm,
        paddingVertical: SPACING.md + 2,
        paddingHorizontal: SPACING.xl,
        borderRadius: RADIUS.lg,
        ...SHADOWS.cardElevated,
    },
    finishButtonText: {
        fontSize: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: '#F5F5F0',
    },
    cancelButton: {
        marginTop: SPACING.xl,
        paddingVertical: SPACING.md,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 15,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.error,
    },
});
