import { StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, RADIUS, SHADOWS, SPACING, TYPOGRAPHY_V2 } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent', 
  },
  content: {
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.xxxl,
  },

  heroSection: {
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.lg,
    backgroundColor: 'transparent',
  },
  heroGreetingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: SPACING.md,
    minHeight: 64,
  },
  brandMark: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkImage: {
    width: 52,
    height: 52,
    borderRadius: 16,
  },
  heroTitleBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroGreeting: {
    fontSize: 30,
    lineHeight: 36,
    fontFamily: FONT_FAMILY.extraBold,
    color: COLORS.text.primary,
    letterSpacing: 0,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 52,
    height: 52,
  },
  heroDate: {
    marginTop: 2,
    fontSize: 16,
    lineHeight: 20,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.accent,
    textTransform: 'uppercase',
    letterSpacing: 2.8,
    textAlign: 'center',
  },
  todayMissionWrap: {
    marginTop: SPACING.lg,
  },
  phaseTransitionWrap: {
    marginTop: SPACING.lg,
  },
  readinessHeroWrap: {
    marginTop: SPACING.lg,
  },
  readinessHeroCard: {
    minHeight: 224,
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.md,
    padding: SPACING.lg,
    borderWidth: 1,
    backgroundColor: 'rgba(10, 10, 10, 0.86)',
    ...SHADOWS.cardElevated,
  },
  readinessHeroCardCompact: {
    minHeight: 286,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  readinessHeroCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-start',
    zIndex: 1,
  },
  readinessHeroCopyCompact: {
    alignItems: 'center',
  },
  readinessHeroKicker: {
    fontSize: 12,
    lineHeight: 15,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.accent,
    letterSpacing: 1,
  },
  readinessHeroTitle: {
    marginTop: SPACING.xs,
    fontSize: 34,
    lineHeight: 39,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.text.primary,
    letterSpacing: 0,
  },
  readinessHeroBody: {
    marginTop: SPACING.xs,
    maxWidth: 190,
    fontSize: 14,
    lineHeight: 20,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.secondary,
  },
  readinessHeroBodyCompact: {
    maxWidth: '100%',
    textAlign: 'center',
  },
  readinessStatusPill: {
    marginTop: SPACING.md,
    minHeight: 34,
    maxWidth: 154,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    paddingHorizontal: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  readinessStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  readinessStatusText: {
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 15,
    fontFamily: FONT_FAMILY.semiBold,
  },
  readinessHeroRingShell: {
    width: 168,
    zIndex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readinessHeroRingShellCompact: {
    width: 156,
    alignSelf: 'center',
  },
  readinessHeroCircleLabel: {
    fontSize: 52,
    lineHeight: 56,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.text.primary,
  },
  readinessHeroCircleSublabel: {
    maxWidth: 90,
    fontSize: 13,
    lineHeight: 16,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
    textAlign: 'center',
  },
  readinessHeroGlow: {
    position: 'absolute',
    right: -78,
    top: -72,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
  },
  readinessHeroAccentLine: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    opacity: 0.9,
  },

  heroMetricsBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(10, 10, 10, 0.78)',
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    marginTop: SPACING.lg,
    gap: SPACING.lg,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.24)',
    ...SHADOWS.cardElevated,
    overflow: 'hidden',
  },
  windowImage: {
    borderRadius: RADIUS.xl,
  },
  windowScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 10, 10, 0.42)',
  },
  readinessScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 10, 10, 0.42)',
  },
  readinessMain: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 138,
  },
  readinessLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
    letterSpacing: 1.6,
    marginBottom: SPACING.sm,
    textTransform: 'uppercase',
  },
  readinessScoreText: {
    fontSize: 44,
    lineHeight: 52,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.text.primary,
  },
  readinessSublabelText: {
    marginTop: SPACING.xs,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.success,
  },
  readinessScoreValue: {
    fontSize: 64,
    fontFamily: FONT_FAMILY.black,
    letterSpacing: 0,
    lineHeight: 72,
  },
  readinessLevel: {
    ...TYPOGRAPHY_V2.plan.caption,
    color: COLORS.text.secondary,
  },

  secondaryMetricsList: {
    flex: 1,
    gap: 0,
    alignItems: 'stretch',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(245, 245, 240, 0.12)',
    paddingLeft: SPACING.md,
  },
  secondaryMetricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingVertical: SPACING.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(245, 245, 240, 0.14)',
    gap: SPACING.sm,
  },
  metricIconBubble: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.32)',
    backgroundColor: 'rgba(10, 10, 10, 0.52)',
  },
  metricCopy: {
    flex: 1,
    minWidth: 0,
  },
  metricTrendBubble: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(183, 217, 168, 0.22)',
    backgroundColor: 'rgba(183, 217, 168, 0.10)',
  },
  secondaryMetricValue: {
    marginTop: 2,
    fontSize: 18,
    lineHeight: 22,
    fontFamily: FONT_FAMILY.extraBold,
    color: COLORS.text.primary,
  },
  secondaryMetricLabel: {
    fontSize: 13,
    lineHeight: 16,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },

  compassCard: {
    marginTop: SPACING.lg,
    backgroundColor: 'rgba(10, 10, 10, 0.64)',
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    minHeight: 236,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(245, 245, 240, 0.25)',
    ...SHADOWS.cardElevated,
  },
  compassWatermark: {
    position: 'absolute',
    right: 22,
    top: 22,
    fontSize: 150,
    lineHeight: 160,
    fontFamily: FONT_FAMILY.black,
    color: 'rgba(212, 175, 55, 0.05)',
  },
  compassHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  compassHeaderCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    minHeight: 42,
  },
  compassTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  missionIconBubble: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.accentLight,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.32)',
  },
  compassSessionRole: {
    flexShrink: 1,
    minWidth: 0,
    fontSize: 18,
    lineHeight: 22,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.accent,
    letterSpacing: 0,
  },
  compassRolePill: {
    maxWidth: '100%',
    fontSize: 11,
    lineHeight: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.secondary,
    letterSpacing: 0.4,
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.full,
    backgroundColor: 'rgba(10, 10, 10, 0.38)',
    overflow: 'hidden',
  },
  compassHeadline: {
    marginTop: SPACING.sm,
    fontSize: 24,
    lineHeight: 30,
    fontFamily: FONT_FAMILY.extraBold,
    color: COLORS.text.primary,
    letterSpacing: 0,
  },
  compassSummary: {
    marginTop: SPACING.xs,
    ...TYPOGRAPHY_V2.plan.body,
    color: COLORS.text.secondary,
  },
  compassReasonRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  compassReasonBar: {
    width: 3,
    borderRadius: 2,
    marginTop: 4,
    minHeight: 14,
    backgroundColor: COLORS.accent,
  },
  compassReasonText: {
    flex: 1,
    ...TYPOGRAPHY_V2.plan.caption,
    color: COLORS.text.secondary,
    letterSpacing: 0,
    lineHeight: 18,
  },
  compassPrimaryButton: {
    marginTop: SPACING.lg,
    minHeight: 58,
    backgroundColor: COLORS.accent,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACING.lg,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.xs,
    ...SHADOWS.colored.accent,
  },
  missionScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 10, 10, 0.28)',
  },
  compassPrimaryText: {
    flexShrink: 1,
    ...TYPOGRAPHY_V2.plan.caption,
    fontSize: 14,
    color: COLORS.text.inverse,
    letterSpacing: 0,
    textAlign: 'center',
  },
  compassSecondaryButton: {
    marginTop: SPACING.sm,
    minHeight: 44,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compassSecondaryText: {
    flexShrink: 1,
    ...TYPOGRAPHY_V2.plan.caption,
    fontSize: 14,
    color: COLORS.text.primary,
    letterSpacing: 0,
    textAlign: 'center',
  },
  compassMissionLink: {
    marginTop: SPACING.md,
    ...TYPOGRAPHY_V2.plan.caption,
    color: COLORS.text.tertiary,
    letterSpacing: 0,
    textAlign: 'center',
  },

  quickActionGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
  },
  quickActionBlock: {
    flex: 1,
    minHeight: 94,
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    backgroundColor: 'transparent',
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: 'rgba(245, 245, 240, 0.18)',
  },
  quickActionBlockDone: {
    backgroundColor: 'transparent',
  },
  quickActionIconContainer: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: 'rgba(10, 10, 10, 0.54)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.34)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionLabelBlock: {
    fontSize: 14,
    lineHeight: 18,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
    letterSpacing: 0,
    textAlign: 'center',
  },
  quickActionLabelDoneBlock: {
    color: COLORS.success,
  },

  contextScheduleNote: {
    fontSize: 13,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.tertiary,
    marginBottom: SPACING.sm,
    lineHeight: 19,
  },

  // Skeleton loading
  skeletonHero: {
    backgroundColor: COLORS.surfaceSecondary,
    padding: SPACING.xl,
    paddingTop: SPACING.xxxl,
  },

  // Chart Overrides for premium look
  chartContainer: {
    height: 200,
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: SPACING.lg,
    marginTop: SPACING.md,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  legendText: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.secondary,
  },
  chartCaption: {
    fontSize: 13,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.tertiary,
    textAlign: 'center',
    marginTop: SPACING.sm,
  },

  // Nutrition/Fuel Overrides
  nutritionCard: {
    padding: SPACING.lg,
  },
  calorieHero: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
    marginBottom: SPACING.lg,
  },
  calorieValue: {
    fontSize: 36,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.text.primary,
    letterSpacing: 0,
  },
  calorieTarget: {
    fontSize: 16,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.tertiary,
    marginLeft: SPACING.xs,
  },
  macroRingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: SPACING.lg,
  },
  macroRingItem: {
    alignItems: 'center',
  },
  macroRingLabel: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
    marginTop: SPACING.sm,
  },
  macroRingSub: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.tertiary,
    marginTop: 2,
  },
  hydrationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingTop: SPACING.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.borderLight,
  },
  hydrationBarWrap: {
    flex: 1,
  },
  hydrationBarBg: {
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.borderLight,
    overflow: 'hidden',
  },
  hydrationBarFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: COLORS.chart.water,
  },
  hydrationText: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.secondary,
  },

  // Biology / Risk Cards
  biologyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
  },
  biologyIcon: {
    width: 44,
    height: 44,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.readiness.cautionLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  biologyInfo: {
    flex: 1,
  },
  biologyTitle: {
    fontSize: 15,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  biologyDesc: {
    fontSize: 13,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.secondary,
    marginTop: 2,
  },

  // Phase control (Moved to bottom conceptually, but styled premium)
  phaseControlHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.sm,
  },
  phaseControlEyebrow: {
    fontSize: 11,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.accent,
    letterSpacing: 1,
  },
  phaseControlCurrentMode: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
    flexShrink: 1,
    maxWidth: '45%',
    textAlign: 'right',
  },
  phaseControlTitle: {
    marginTop: SPACING.xs,
    fontSize: 20,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.text.primary,
    letterSpacing: 0,
    lineHeight: 26,
  },
  phaseControlDescription: {
    marginTop: SPACING.xs,
    fontSize: 14,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.secondary,
    lineHeight: 20,
  },
  phaseControlSummaryRow: {
    marginTop: SPACING.md,
    flexDirection: 'column',
    alignItems: 'stretch',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.borderLight,
    borderRadius: RADIUS.lg,
    overflow: 'hidden',
    backgroundColor: COLORS.surfaceSecondary,
  },
  phaseControlSummaryBlock: {
    flex: 1,
    paddingVertical: SPACING.sm + 2,
    paddingHorizontal: SPACING.md,
  },
  phaseControlSummaryDivider: {
    width: '100%',
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.borderLight,
  },
  phaseControlSummaryLabel: {
    fontSize: 11,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  phaseControlSummaryValue: {
    marginTop: 4,
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  phaseControlPrimaryButton: {
    marginTop: SPACING.md,
    backgroundColor: COLORS.accent,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    paddingVertical: SPACING.md,
  },
  phaseControlPrimaryText: {
    fontSize: 15,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.inverse,
  },
  phaseControlSecondaryButton: {
    marginTop: SPACING.sm,
    borderRadius: RADIUS.full,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.md - 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  phaseControlSecondaryText: {
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },

  // First-run guidance
  firstRunModalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: 'center',
    paddingHorizontal: SPACING.lg,
  },
  firstRunModalCard: {
    backgroundColor: '#0A0A0A', // Slate 900
    borderRadius: RADIUS.xxl,
    padding: SPACING.xl,
    maxHeight: '86%',
    ...SHADOWS.md,
  },
  firstRunModalContent: {
    flexGrow: 1,
  },
  firstRunModalKicker: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.readiness.prime,
    letterSpacing: 2,
  },
  firstRunModalTitle: {
    marginTop: SPACING.xs,
    fontSize: 32,
    fontFamily: FONT_FAMILY.black,
    color: '#F5F5F0',
    letterSpacing: 0,
  },
  firstRunModalBody: {
    marginTop: SPACING.sm,
    fontSize: 16,
    fontFamily: FONT_FAMILY.regular,
    color: 'rgba(255,255,255,0.8)',
    lineHeight: 24,
  },
  firstRunModalPrimaryButton: {
    marginTop: SPACING.xl,
    backgroundColor: '#F5F5F0',
    borderRadius: RADIUS.full,
    alignItems: 'center',
    paddingVertical: SPACING.md,
  },
  firstRunModalPrimaryText: {
    fontSize: 16,
    fontFamily: FONT_FAMILY.black,
    color: '#0A0A0A',
  },
  firstRunModalSecondaryButton: {
    marginTop: SPACING.md,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: RADIUS.full,
    alignItems: 'center',
    paddingVertical: SPACING.md,
  },
  firstRunModalSecondaryText: {
    fontSize: 15,
    fontFamily: FONT_FAMILY.semiBold,
    color: '#F5F5F0',
  },
  firstRunHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: SPACING.sm,
  },
  firstRunChecklistAfterBodyTrend: {
    marginTop: SPACING.md,
  },
  firstRunKicker: {
    fontSize: 11,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.accent,
    letterSpacing: 1,
  },
  firstRunProgress: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
    flexShrink: 1,
    textAlign: 'right',
  },
  firstRunTitle: {
    marginTop: SPACING.xs,
    fontSize: 20,
    fontFamily: FONT_FAMILY.black,
    color: COLORS.text.primary,
    letterSpacing: 0,
  },
  firstRunSubtitle: {
    marginTop: SPACING.xs,
    fontSize: 13,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.secondary,
    lineHeight: 20,
  },
  firstRunStepList: {
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  firstRunStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.borderLight,
    borderRadius: RADIUS.lg,
    padding: SPACING.sm,
    gap: SPACING.sm,
    backgroundColor: COLORS.surfaceSecondary,
  },
  firstRunStepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.surface,
  },
  firstRunStepBadgeDone: {
    borderColor: COLORS.success,
    backgroundColor: COLORS.success + '20',
  },
  firstRunStepBadgeText: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.secondary,
  },
  firstRunStepBadgeTextDone: {
    color: COLORS.success,
  },
  firstRunStepCopy: {
    flex: 1,
    flexShrink: 1,
  },
  firstRunStepTitle: {
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  firstRunStepSubtitle: {
    marginTop: 2,
    fontSize: 12,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.tertiary,
    lineHeight: 17,
  },
  firstRunStepCta: {
    fontSize: 12,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.accent,
    alignSelf: 'center',
  },

  // Why Today? expandable
  whyTodayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: SPACING.xs,
  },
  whyTodayTitle: {
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  whyTodayChevron: {
    fontSize: 11,
    color: COLORS.text.tertiary,
  },
  whyTodayItem: {
    marginTop: SPACING.sm,
    paddingTop: SPACING.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.borderLight,
  },
  whyTodayItemTitle: {
    fontSize: 13,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  whyTodayItemSentence: {
    marginTop: 2,
    fontSize: 13,
    fontFamily: FONT_FAMILY.regular,
    color: COLORS.text.secondary,
    lineHeight: 19,
  },
});
