import { StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, SPACING, RADIUS, SHADOWS } from '../theme/theme';

const SCREEN_HORIZONTAL_PADDING = 18;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    appBackdrop: {
        ...StyleSheet.absoluteFillObject,
        overflow: 'hidden',
    },
    backdropGoldWash: {
        position: 'absolute',
        top: -120,
        right: -140,
        width: 280,
        height: 280,
        borderRadius: 140,
        backgroundColor: 'rgba(212, 175, 55, 0.13)',
    },
    backdropPearlWash: {
        position: 'absolute',
        bottom: 90,
        left: -170,
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: 'rgba(245, 245, 240, 0.045)',
    },
    inner: {
        flex: 1,
        paddingHorizontal: SCREEN_HORIZONTAL_PADDING,
    },
    topNav: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: SPACING.sm,
        marginBottom: SPACING.md,
        minHeight: 48,
    },
    brandHeader: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
    },
    brandMarkImage: {
        width: 42,
        height: 42,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.28)',
    },
    brandTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    brandEyebrow: {
        fontSize: 10,
        lineHeight: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1.6,
    },
    brandTitle: {
        marginTop: 2,
        fontSize: 17,
        lineHeight: 21,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
    },
    signOutButtonIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
        paddingHorizontal: SPACING.sm + 2,
        borderRadius: RADIUS.full,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.16)',
        backgroundColor: 'rgba(10, 10, 10, 0.62)',
    },
    signOutButtonText: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        marginLeft: 4,
    },
    progressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.md,
        marginBottom: SPACING.sm + 2,
    },
    progressTrack: {
        flex: 1,
        height: 5,
        backgroundColor: 'rgba(245, 245, 240, 0.12)',
        borderRadius: RADIUS.full,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: COLORS.accent,
        borderRadius: RADIUS.full,
    },
    stepIndicator: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    phaseCard: {
        minHeight: 178,
        backgroundColor: 'rgba(10, 10, 10, 0.78)',
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.34)',
        borderRadius: 26,
        padding: SPACING.lg,
        marginBottom: SPACING.md,
        overflow: 'hidden',
        ...SHADOWS.cardElevated,
    },
    phaseCardImage: {
        borderRadius: 26,
    },
    phaseCardScrim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 10, 10, 0.52)',
    },
    phaseMetalLine: {
        position: 'absolute',
        top: 0,
        left: SPACING.xl,
        right: SPACING.xl,
        height: 1,
        backgroundColor: 'rgba(212, 175, 55, 0.52)',
    },
    phaseCardKeyboard: {
        padding: SPACING.md,
        marginBottom: SPACING.md,
        minHeight: 132,
    },
    phaseHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
    },
    phaseStepBadge: {
        width: 46,
        height: 46,
        borderRadius: 23,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.54)',
        backgroundColor: 'rgba(10, 10, 10, 0.54)',
    },
    phaseStepBadgeText: {
        fontSize: 18,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.accent,
    },
    phaseHeaderCopy: {
        flex: 1,
        minWidth: 0,
    },
    phaseStepPill: {
        fontSize: 12,
        lineHeight: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
        borderRadius: RADIUS.full,
        overflow: 'hidden',
        backgroundColor: 'rgba(10, 10, 10, 0.46)',
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.12)',
    },
    phaseEyebrow: {
        fontSize: 12,
        lineHeight: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        textTransform: 'uppercase',
        letterSpacing: 1.2,
    },
    phaseTitle: {
        marginTop: 2,
        fontSize: 28,
        lineHeight: 34,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
    },
    phaseDescription: {
        marginTop: SPACING.md,
        fontSize: 15,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        maxWidth: '92%',
    },
    phaseMetaRow: {
        flexDirection: 'row',
        gap: SPACING.sm,
        flexWrap: 'wrap',
        marginTop: SPACING.md,
    },
    phaseMetaPill: {
        overflow: 'hidden',
        borderRadius: RADIUS.full,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.28)',
        backgroundColor: 'rgba(10, 10, 10, 0.44)',
        paddingHorizontal: SPACING.sm + 2,
        paddingVertical: 5,
        fontSize: 10,
        lineHeight: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: SPACING.md,
    },
    scrollContentKeyboard: {
        paddingBottom: SPACING.xxxl,
    },
    stepContent: {
        flex: 1,
        gap: SPACING.md,
    },
    welcomePanel: {
        minHeight: 258,
        borderRadius: RADIUS.xl,
        overflow: 'hidden',
        padding: SPACING.lg,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.24)',
        backgroundColor: 'rgba(10, 10, 10, 0.72)',
        ...SHADOWS.cardElevated,
    },
    welcomePanelImage: {
        borderRadius: RADIUS.xl,
    },
    welcomePanelScrim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 10, 10, 0.44)',
    },
    welcomeHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        marginBottom: SPACING.xl,
    },
    welcomeIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 54,
        height: 54,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.28)',
        backgroundColor: 'rgba(10, 10, 10, 0.46)',
    },
    welcomeLogo: {
        width: 48,
        height: 48,
        borderRadius: 16,
    },
    welcomeHeaderCopy: {
        flex: 1,
        minWidth: 0,
    },
    welcomeKicker: {
        fontSize: 12,
        lineHeight: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1.4,
    },
    welcomeSignal: {
        marginTop: 2,
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    welcomeTitle: {
        fontSize: 30,
        lineHeight: 36,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
        marginBottom: SPACING.md,
    },
    welcomeSubtitle: {
        fontSize: 16,
        lineHeight: 24,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        maxWidth: '96%',
    },
    signalStrip: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderRadius: RADIUS.xl,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.24)',
        backgroundColor: 'rgba(10, 10, 10, 0.70)',
        paddingVertical: SPACING.md,
        paddingHorizontal: SPACING.md,
        ...SHADOWS.card,
    },
    signalMetric: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    signalMetricValue: {
        fontSize: 17,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0.8,
    },
    signalMetricLabel: {
        marginTop: 2,
        fontSize: 10,
        lineHeight: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        letterSpacing: 1.1,
        textTransform: 'uppercase',
    },
    signalMetricDivider: {
        width: 1,
        height: 36,
        backgroundColor: 'rgba(245, 245, 240, 0.12)',
    },
    coachPointList: {
        gap: SPACING.sm,
        marginTop: 0,
    },
    coachPoint: {
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(12, 12, 12, 0.78)',
        paddingVertical: SPACING.sm + 4,
        paddingHorizontal: SPACING.md,
        overflow: 'hidden',
        ...SHADOWS.card,
    },
    standaloneCoachPoint: {
        marginTop: 0,
    },
    coachPointRail: {
        position: 'absolute',
        left: 0,
        top: SPACING.md,
        bottom: SPACING.md,
        width: 3,
        borderRadius: 2,
        backgroundColor: 'rgba(212, 175, 55, 0.72)',
    },
    coachPointTitle: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
        marginBottom: 3,
    },
    coachPointText: {
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    safetyCard: {
        borderRadius: RADIUS.xl,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.24)',
        backgroundColor: 'rgba(212, 175, 55, 0.10)',
        padding: SPACING.md,
    },
    safetyKicker: {
        fontSize: 11,
        lineHeight: 15,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1.2,
    },
    safetyText: {
        marginTop: 4,
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    stepTitle: {
        fontSize: 26,
        lineHeight: 32,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
        marginBottom: SPACING.xs,
    },
    stepSubtitle: {
        fontSize: 15,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        marginBottom: SPACING.xl,
    },
    inputGroup: {
        marginBottom: SPACING.lg,
    },
    inputRow: {
        flexDirection: 'row',
    },
    inputLabel: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        marginBottom: SPACING.xs,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    input: {
        minHeight: 52,
        backgroundColor: 'rgba(10, 10, 10, 0.62)',
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.18)',
        padding: SPACING.md,
        fontSize: 16,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.primary,
    },
    helperText: {
        fontSize: 13,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.tertiary,
        marginBottom: SPACING.sm,
    },
    baselineDetailsCard: {
        borderRadius: RADIUS.xl,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.16)',
        backgroundColor: 'rgba(12, 12, 12, 0.82)',
        padding: SPACING.md,
        marginBottom: 0,
        ...SHADOWS.card,
    },
    baselineDetailsTitle: {
        fontSize: 17,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
    },
    baselineDetailsCopy: {
        marginTop: SPACING.xs,
        marginBottom: SPACING.md,
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    baselineFieldStack: {
        flexDirection: 'row',
        alignItems: 'stretch',
        gap: SPACING.sm,
    },
    baselineField: {
        flex: 1,
        minHeight: 112,
        justifyContent: 'space-between',
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.12)',
        backgroundColor: 'rgba(245, 245, 240, 0.055)',
        padding: SPACING.sm + 2,
    },
    baselineLabelRow: {
        minHeight: 36,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        gap: 2,
        marginBottom: SPACING.sm,
    },
    baselineFieldLabel: {
        width: '100%',
        fontSize: 11,
        lineHeight: 15,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    baselineFieldMeta: {
        fontSize: 10,
        lineHeight: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    baselineInput: {
        minHeight: 52,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.22)',
        backgroundColor: 'rgba(10, 10, 10, 0.66)',
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.xs,
        fontSize: 17,
        lineHeight: 23,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    baselineNumericText: {
        fontSize: 17,
        lineHeight: 23,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
        textAlign: 'center',
    },
    formGlassSection: {
        borderRadius: RADIUS.xl,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(12, 12, 12, 0.78)',
        padding: SPACING.md,
        ...SHADOWS.card,
    },
    segmentGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.sm,
    },
    segmentGridCompact: {
        flexWrap: 'nowrap',
    },
    segmentButton: {
        flexGrow: 1,
        width: '47%',
        minHeight: 68,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.60)',
        paddingVertical: SPACING.sm + 2,
        paddingHorizontal: SPACING.md,
        justifyContent: 'center',
    },
    segmentButtonCompact: {
        flex: 1,
        width: undefined,
        minHeight: 48,
        alignItems: 'center',
        paddingHorizontal: SPACING.sm,
    },
    segmentButtonActive: {
        borderColor: 'rgba(212, 175, 55, 0.52)',
        backgroundColor: COLORS.accentLight,
    },
    segmentTitle: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    segmentTitleActive: {
        color: COLORS.accent,
    },
    segmentDescription: {
        marginTop: 3,
        fontSize: 12,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    segmentDescriptionActive: {
        color: COLORS.text.secondary,
    },
    dayGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.sm,
    },
    dayCard: {
        flexGrow: 1,
        width: '30.5%',
        minHeight: 58,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.sm,
    },
    dayCardActive: {
        borderColor: 'rgba(212, 175, 55, 0.48)',
        backgroundColor: COLORS.accentLight,
        ...SHADOWS.colored.accent,
    },
    dayCardLabel: {
        fontSize: 16,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
    },
    dayCardLabelActive: {
        color: COLORS.accent,
    },
    dayCardCaption: {
        marginTop: 2,
        fontSize: 11,
        lineHeight: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    dayCardCaptionActive: {
        color: COLORS.text.secondary,
    },
    pillRow: {
        flexDirection: 'row',
        gap: SPACING.sm,
        flexWrap: 'wrap',
    },
    pill: {
        minHeight: 42,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        borderRadius: RADIUS.full,
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.16)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    pillActive: {
        backgroundColor: COLORS.accent,
        borderColor: COLORS.accent,
        ...SHADOWS.colored.accent,
    },
    pillText: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    pillTextActive: {
        color: COLORS.text.inverse,
    },
    pillDescriptor: {
        marginTop: 2,
        fontSize: 11,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.tertiary,
    },
    pillDescriptorActive: {
        color: COLORS.text.inverse,
        opacity: 0.9,
    },
    effortGrid: {
        flexDirection: 'row',
        gap: SPACING.sm,
    },
    effortCard: {
        flex: 1,
        minHeight: 72,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        padding: SPACING.sm,
        justifyContent: 'space-between',
    },
    effortCardActive: {
        borderColor: 'rgba(212, 175, 55, 0.48)',
        backgroundColor: COLORS.accentLight,
    },
    effortCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: SPACING.xs,
    },
    effortValue: {
        fontSize: 22,
        lineHeight: 27,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.text.primary,
    },
    effortValueActive: {
        color: COLORS.accent,
    },
    effortLabel: {
        marginTop: SPACING.xs,
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    effortLabelActive: {
        color: COLORS.text.primary,
    },
    tooltipBadge: {
        width: 22,
        height: 22,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.18)',
        backgroundColor: 'rgba(10, 10, 10, 0.42)',
    },
    tooltipBadgeActive: {
        borderColor: 'rgba(212, 175, 55, 0.40)',
        backgroundColor: 'rgba(212, 175, 55, 0.16)',
    },
    tooltipBadgeText: {
        fontSize: 12,
        lineHeight: 15,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.text.tertiary,
    },
    tooltipBadgeTextActive: {
        color: COLORS.accent,
    },
    effortTooltip: {
        marginTop: SPACING.sm,
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.20)',
        backgroundColor: 'rgba(212, 175, 55, 0.10)',
        padding: SPACING.md,
    },
    effortTooltipTitle: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    effortTooltipText: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    activityOptionsList: {
        gap: SPACING.sm,
    },
    activityOptionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        paddingVertical: SPACING.sm,
        paddingHorizontal: SPACING.md,
        minHeight: 58,
    },
    activityOptionCardActive: {
        borderColor: 'rgba(212, 175, 55, 0.46)',
        backgroundColor: COLORS.accentLight,
    },
    activityOptionCopy: {
        flex: 1,
        paddingRight: SPACING.sm,
    },
    activityOptionTitle: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    activityOptionTitleActive: {
        color: COLORS.accent,
    },
    activityOptionDescription: {
        marginTop: 2,
        fontSize: 12,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    activityOptionDescriptionActive: {
        color: COLORS.text.secondary,
    },
    activityOptionIndicator: {
        width: 26,
        height: 26,
        borderRadius: 13,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.18)',
        backgroundColor: 'rgba(10, 10, 10, 0.42)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    activityOptionIndicatorActive: {
        borderColor: 'rgba(212, 175, 55, 0.42)',
        backgroundColor: 'rgba(245, 245, 240, 0.10)',
    },
    optionalBlock: {
        marginTop: SPACING.md,
        paddingTop: SPACING.md,
        borderTopWidth: 1,
        borderTopColor: 'rgba(245, 245, 240, 0.12)',
    },
    optionalHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: SPACING.md,
        marginBottom: SPACING.md,
    },
    addSmallButton: {
        minHeight: 44,
        paddingHorizontal: SPACING.lg,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.accentLight,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.28)',
    },
    addSmallButtonActive: {
        backgroundColor: COLORS.accent,
        borderColor: COLORS.accent,
        ...SHADOWS.colored.accent,
    },
    addSmallButtonText: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    addSmallButtonTextActive: {
        color: COLORS.text.inverse,
    },
    fixedSessionStack: {
        gap: SPACING.md,
        marginTop: SPACING.xs,
    },
    fixedSessionCard: {
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.20)',
        backgroundColor: 'rgba(10, 10, 10, 0.64)',
        padding: SPACING.md,
        marginBottom: 0,
        ...SHADOWS.card,
    },
    fixedSessionCardNew: {
        borderColor: 'rgba(212, 175, 55, 0.62)',
        backgroundColor: 'rgba(212, 175, 55, 0.11)',
        ...SHADOWS.colored.accent,
    },
    fixedSessionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: SPACING.md,
        marginBottom: SPACING.md,
    },
    fixedSessionTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    fixedSessionEyebrowRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        marginBottom: 3,
    },
    fixedSessionEyebrow: {
        fontSize: 10,
        lineHeight: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    newSessionBadge: {
        overflow: 'hidden',
        borderRadius: RADIUS.full,
        backgroundColor: COLORS.accent,
        paddingHorizontal: SPACING.sm,
        paddingVertical: 2,
        fontSize: 10,
        lineHeight: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.inverse,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    fixedSessionTitle: {
        flex: 1,
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    sessionTypeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.sm,
    },
    sessionTypeButton: {
        width: '48.5%',
        minHeight: 46,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(245, 245, 240, 0.055)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.sm,
    },
    sessionTypeButtonFull: {
        width: '100%',
    },
    sessionTypeButtonActive: {
        borderColor: 'rgba(212, 175, 55, 0.56)',
        backgroundColor: COLORS.accent,
        ...SHADOWS.colored.accent,
    },
    sessionTypeText: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        textAlign: 'center',
    },
    sessionTypeTextActive: {
        color: COLORS.text.inverse,
    },
    removeText: {
        fontSize: 13,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.readiness.depleted,
    },
    missionPreviewCard: {
        borderRadius: 26,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.32)',
        backgroundColor: 'rgba(12, 12, 12, 0.82)',
        padding: SPACING.lg,
        overflow: 'hidden',
        ...SHADOWS.cardElevated,
    },
    missionPreviewKicker: {
        fontSize: 11,
        lineHeight: 15,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1.4,
    },
    missionPreviewTitle: {
        marginTop: SPACING.sm,
        fontSize: 22,
        lineHeight: 28,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
    },
    missionPreviewText: {
        marginTop: SPACING.sm,
        fontSize: 14,
        lineHeight: 21,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    navRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: SPACING.md,
        paddingTop: SPACING.sm,
        paddingHorizontal: SPACING.sm,
        borderTopWidth: 1,
        borderTopColor: 'rgba(245, 245, 240, 0.10)',
        backgroundColor: 'rgba(10, 10, 10, 0.76)',
        borderRadius: RADIUS.xl,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.xs,
        minHeight: 44,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.sm,
        borderRadius: RADIUS.full,
    },
    backText: {
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    nextButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.xs,
        minHeight: 54,
        paddingHorizontal: SPACING.xl,
        paddingVertical: SPACING.md,
        borderRadius: RADIUS.full,
        backgroundColor: COLORS.accent,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.24)',
        ...SHADOWS.colored.accent,
    },
    nextButtonDisabled: {
        opacity: 0.4,
    },
    nextText: {
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.inverse,
    },
    keyboardAccessory: {
        alignSelf: 'stretch',
        minHeight: 60,
        marginHorizontal: -SCREEN_HORIZONTAL_PADDING,
        marginTop: 0,
        paddingHorizontal: 12,
        paddingVertical: SPACING.sm,
        alignItems: 'flex-end',
        justifyContent: 'center',
        backgroundColor: '#202020',
        borderTopWidth: 1,
        borderTopColor: 'rgba(245, 245, 240, 0.16)',
        ...SHADOWS.card,
    },
    keyboardDoneButton: {
        minHeight: 44,
        minWidth: 92,
        paddingHorizontal: SPACING.md + SPACING.sm,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.accent,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.28)',
        ...SHADOWS.colored.accent,
    },
    keyboardDoneText: {
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.inverse,
    },
});
