import { StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, SPACING, RADIUS, SHADOWS } from '../theme/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    inner: {
        flex: 1,
        paddingHorizontal: SPACING.lg,
    },
    topNav: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: SPACING.md,
        marginBottom: SPACING.lg,
        minHeight: 52,
    },
    brandHeader: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
    },
    brandMarkImage: {
        width: 44,
        height: 44,
        borderRadius: 14,
    },
    brandTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    brandEyebrow: {
        fontSize: 10,
        lineHeight: 13,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1.6,
    },
    brandTitle: {
        marginTop: 2,
        fontSize: 18,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
    },
    signOutButtonIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
        paddingHorizontal: SPACING.sm,
        borderRadius: RADIUS.full,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.12)',
        backgroundColor: 'rgba(10, 10, 10, 0.34)',
    },
    signOutButtonText: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        marginLeft: 4,
    },
    progressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.md,
        marginBottom: SPACING.md,
    },
    progressTrack: {
        flex: 1,
        height: 6,
        backgroundColor: 'rgba(245, 245, 240, 0.12)',
        borderRadius: RADIUS.full,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: COLORS.accent,
        borderRadius: RADIUS.full,
    },
    stepIndicator: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    phaseCard: {
        minHeight: 158,
        backgroundColor: 'rgba(10, 10, 10, 0.78)',
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.24)',
        borderRadius: RADIUS.xl,
        padding: SPACING.lg,
        marginBottom: SPACING.lg,
        overflow: 'hidden',
        ...SHADOWS.cardElevated,
    },
    phaseCardImage: {
        borderRadius: RADIUS.xl,
    },
    phaseCardScrim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 10, 10, 0.46)',
    },
    phaseCardKeyboard: {
        padding: SPACING.md,
        marginBottom: SPACING.md,
        minHeight: 126,
    },
    phaseHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
    },
    phaseStepBadge: {
        width: 42,
        height: 42,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.34)',
        backgroundColor: COLORS.accentLight,
    },
    phaseStepBadgeText: {
        fontSize: 18,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.accent,
    },
    phaseHeaderCopy: {
        flex: 1,
        minWidth: 0,
    },
    phaseStepPill: {
        fontSize: 12,
        lineHeight: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
        borderRadius: RADIUS.full,
        overflow: 'hidden',
        backgroundColor: 'rgba(10, 10, 10, 0.46)',
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.12)',
    },
    phaseEyebrow: {
        fontSize: 12,
        lineHeight: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        textTransform: 'uppercase',
        letterSpacing: 1.2,
    },
    phaseTitle: {
        marginTop: 2,
        fontSize: 24,
        lineHeight: 30,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
    },
    phaseDescription: {
        marginTop: SPACING.md,
        fontSize: 14,
        lineHeight: 21,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        maxWidth: '88%',
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: SPACING.lg,
    },
    scrollContentKeyboard: {
        paddingBottom: SPACING.xs,
    },
    stepContent: {
        flex: 1,
    },
    welcomePanel: {
        minHeight: 258,
        borderRadius: RADIUS.xl,
        overflow: 'hidden',
        padding: SPACING.lg,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.24)',
        backgroundColor: 'rgba(10, 10, 10, 0.72)',
        ...SHADOWS.cardElevated,
    },
    welcomePanelImage: {
        borderRadius: RADIUS.xl,
    },
    welcomePanelScrim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(10, 10, 10, 0.44)',
    },
    welcomeHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        marginBottom: SPACING.xl,
    },
    welcomeIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 54,
        height: 54,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.28)',
        backgroundColor: 'rgba(10, 10, 10, 0.46)',
    },
    welcomeLogo: {
        width: 48,
        height: 48,
        borderRadius: 16,
    },
    welcomeHeaderCopy: {
        flex: 1,
        minWidth: 0,
    },
    welcomeKicker: {
        fontSize: 12,
        lineHeight: 16,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
        letterSpacing: 1.4,
    },
    welcomeSignal: {
        marginTop: 2,
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    welcomeTitle: {
        fontSize: 30,
        lineHeight: 36,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
        marginBottom: SPACING.md,
    },
    welcomeSubtitle: {
        fontSize: 16,
        lineHeight: 24,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        maxWidth: '96%',
    },
    coachPointList: {
        gap: SPACING.sm,
        marginTop: SPACING.lg,
    },
    coachPoint: {
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.20)',
        backgroundColor: 'rgba(10, 10, 10, 0.70)',
        padding: SPACING.md,
        overflow: 'hidden',
        ...SHADOWS.card,
    },
    coachPointRail: {
        position: 'absolute',
        left: 0,
        top: SPACING.md,
        bottom: SPACING.md,
        width: 3,
        borderRadius: 2,
        backgroundColor: 'rgba(212, 175, 55, 0.72)',
    },
    coachPointTitle: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
        marginBottom: 3,
    },
    coachPointText: {
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    stepTitle: {
        fontSize: 26,
        lineHeight: 32,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
        letterSpacing: 0,
        marginBottom: SPACING.xs,
    },
    stepSubtitle: {
        fontSize: 15,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        marginBottom: SPACING.xl,
    },
    inputGroup: {
        marginBottom: SPACING.lg,
    },
    inputRow: {
        flexDirection: 'row',
    },
    inputLabel: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
        marginBottom: SPACING.xs,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    input: {
        minHeight: 52,
        backgroundColor: 'rgba(10, 10, 10, 0.62)',
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.18)',
        padding: SPACING.md,
        fontSize: 16,
        lineHeight: 22,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.primary,
    },
    helperText: {
        fontSize: 13,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.tertiary,
        marginBottom: SPACING.sm,
    },
    dayGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: SPACING.sm,
    },
    dayCard: {
        flexGrow: 1,
        width: '30.5%',
        minHeight: 64,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.sm,
    },
    dayCardActive: {
        borderColor: 'rgba(212, 175, 55, 0.48)',
        backgroundColor: COLORS.accentLight,
        ...SHADOWS.colored.accent,
    },
    dayCardLabel: {
        fontSize: 16,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.extraBold,
        color: COLORS.text.primary,
    },
    dayCardLabelActive: {
        color: COLORS.accent,
    },
    dayCardCaption: {
        marginTop: 2,
        fontSize: 11,
        lineHeight: 14,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    dayCardCaptionActive: {
        color: COLORS.text.secondary,
    },
    pillRow: {
        flexDirection: 'row',
        gap: SPACING.sm,
        flexWrap: 'wrap',
    },
    pill: {
        minHeight: 44,
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.sm + 4,
        borderRadius: RADIUS.full,
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.16)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    pillActive: {
        backgroundColor: COLORS.accent,
        borderColor: COLORS.accent,
        ...SHADOWS.colored.accent,
    },
    pillText: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    pillTextActive: {
        color: COLORS.text.inverse,
    },
    pillDescriptor: {
        marginTop: 2,
        fontSize: 11,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.tertiary,
    },
    pillDescriptorActive: {
        color: COLORS.text.inverse,
        opacity: 0.9,
    },
    effortGrid: {
        flexDirection: 'row',
        gap: SPACING.sm,
    },
    effortCard: {
        flex: 1,
        minHeight: 78,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.58)',
        padding: SPACING.sm,
        justifyContent: 'space-between',
    },
    effortCardActive: {
        borderColor: 'rgba(212, 175, 55, 0.48)',
        backgroundColor: COLORS.accentLight,
    },
    effortCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: SPACING.xs,
    },
    effortValue: {
        fontSize: 22,
        lineHeight: 27,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.text.primary,
    },
    effortValueActive: {
        color: COLORS.accent,
    },
    effortLabel: {
        marginTop: SPACING.xs,
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    effortLabelActive: {
        color: COLORS.text.primary,
    },
    tooltipBadge: {
        width: 22,
        height: 22,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.18)',
        backgroundColor: 'rgba(10, 10, 10, 0.42)',
    },
    tooltipBadgeActive: {
        borderColor: 'rgba(212, 175, 55, 0.40)',
        backgroundColor: 'rgba(212, 175, 55, 0.16)',
    },
    tooltipBadgeText: {
        fontSize: 12,
        lineHeight: 15,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.text.tertiary,
    },
    tooltipBadgeTextActive: {
        color: COLORS.accent,
    },
    effortTooltip: {
        marginTop: SPACING.sm,
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.20)',
        backgroundColor: 'rgba(212, 175, 55, 0.10)',
        padding: SPACING.md,
    },
    effortTooltipTitle: {
        fontSize: 13,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    effortTooltipText: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 19,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    activityOptionsList: {
        gap: SPACING.sm,
    },
    activityOptionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.14)',
        backgroundColor: 'rgba(10, 10, 10, 0.64)',
        paddingVertical: SPACING.sm + 2,
        paddingHorizontal: SPACING.md,
        minHeight: 64,
    },
    activityOptionCardActive: {
        borderColor: 'rgba(212, 175, 55, 0.46)',
        backgroundColor: COLORS.accentLight,
    },
    activityOptionCopy: {
        flex: 1,
        paddingRight: SPACING.sm,
    },
    activityOptionTitle: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    activityOptionTitleActive: {
        color: COLORS.accent,
    },
    activityOptionDescription: {
        marginTop: 2,
        fontSize: 12,
        lineHeight: 17,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
    },
    activityOptionDescriptionActive: {
        color: COLORS.text.secondary,
    },
    activityOptionIndicator: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.18)',
        backgroundColor: 'rgba(10, 10, 10, 0.42)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    activityOptionIndicatorActive: {
        borderColor: 'rgba(212, 175, 55, 0.42)',
        backgroundColor: 'rgba(245, 245, 240, 0.10)',
    },
    optionalBlock: {
        marginTop: SPACING.xl,
        paddingTop: SPACING.lg,
        borderTopWidth: 1,
        borderTopColor: 'rgba(245, 245, 240, 0.12)',
    },
    optionalHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: SPACING.md,
        marginBottom: SPACING.md,
    },
    addSmallButton: {
        minHeight: 44,
        paddingHorizontal: SPACING.lg,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.accentLight,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.28)',
    },
    addSmallButtonText: {
        fontSize: 14,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.accent,
    },
    fixedSessionCard: {
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.20)',
        backgroundColor: 'rgba(10, 10, 10, 0.70)',
        padding: SPACING.md,
        marginBottom: SPACING.md,
        ...SHADOWS.card,
    },
    fixedSessionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: SPACING.md,
        marginBottom: SPACING.md,
    },
    fixedSessionTitle: {
        flex: 1,
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.primary,
    },
    removeText: {
        fontSize: 13,
        lineHeight: 18,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.readiness.depleted,
    },
    navRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: SPACING.md,
        paddingTop: SPACING.md,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: 'rgba(245, 245, 240, 0.12)',
    },
    navRowKeyboard: {
        paddingTop: SPACING.xs,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.xs,
        minHeight: 44,
        padding: SPACING.sm,
        borderRadius: RADIUS.full,
    },
    backText: {
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.secondary,
    },
    nextButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.xs,
        minHeight: 52,
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.sm + 6,
        borderRadius: RADIUS.full,
        backgroundColor: COLORS.accent,
        borderWidth: 1,
        borderColor: 'rgba(245, 245, 240, 0.24)',
        ...SHADOWS.colored.accent,
    },
    nextButtonDisabled: {
        opacity: 0.4,
    },
    nextText: {
        fontSize: 15,
        lineHeight: 20,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.inverse,
    },
});
