import { StyleSheet } from 'react-native';
import { COLORS, FONT_FAMILY, SPACING, RADIUS, SHADOWS } from '../theme/theme';

export const styles = StyleSheet.create({
    header: {
        paddingBottom: SPACING.lg,
        paddingHorizontal: SPACING.lg,
        gap: SPACING.sm,
    },
    backButton: { marginBottom: SPACING.xs },
    headerTitle: { fontSize: 22, fontFamily: FONT_FAMILY.black, color: COLORS.text.primary },
    stepDots: { flexDirection: 'row', gap: 6, marginTop: SPACING.sm },
    dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.border },
    dotActive: { backgroundColor: COLORS.accent },

    stepContainer: { gap: SPACING.md },
    stepTitle: { fontSize: 12, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.tertiary, letterSpacing: 1, textTransform: 'uppercase' },
    heading: { fontSize: 28, fontFamily: FONT_FAMILY.black, color: COLORS.text.primary },
    subtitle: { fontSize: 14, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary },
    label: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary, marginTop: SPACING.sm },

    // ── Step 1: Intro ─────────────────────────────────────────────
    introHero: {
        alignItems: 'center',
        backgroundColor: 'rgba(10, 10, 10, 0.78)',
        borderWidth: 1,
        borderColor: 'rgba(212, 175, 55, 0.26)',
        borderRadius: RADIUS.xl,
        padding: SPACING.xl,
        gap: SPACING.sm,
        marginBottom: SPACING.sm,
    },
    introHeroEmoji: { fontSize: 48 },
    introHeroTitle: {
        fontSize: 22,
        fontFamily: FONT_FAMILY.black,
        color: COLORS.text.primary,
        textAlign: 'center',
    },
    introHeroSub: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        textAlign: 'center',
        lineHeight: 22,
    },
    introSectionLabel: {
        fontSize: 11,
        fontFamily: FONT_FAMILY.semiBold,
        color: COLORS.text.tertiary,
        letterSpacing: 1.2,
        textTransform: 'uppercase',
        marginBottom: SPACING.xs,
    },
    impactCard: {
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        padding: SPACING.md,
        gap: SPACING.sm,
    },
    impactCardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.md,
    },
    impactIconBox: {
        width: 44,
        height: 44,
        borderRadius: RADIUS.md,
        justifyContent: 'center',
        alignItems: 'center',
    },
    impactIcon: { fontSize: 22 },
    impactFeature: {
        fontSize: 16,
        fontFamily: FONT_FAMILY.semiBold,
    },
    impactTimingBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: RADIUS.full,
        marginTop: 3,
    },
    impactTiming: {
        fontSize: 11,
        fontFamily: FONT_FAMILY.semiBold,
    },
    impactDetail: {
        fontSize: 13,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        lineHeight: 20,
    },
    phaseCard: {
        flexDirection: 'row',
        borderRadius: RADIUS.lg,
        overflow: 'hidden',
        gap: SPACING.md,
        padding: SPACING.md,
        alignItems: 'flex-start',
    },
    phaseCardBar: {
        width: 4,
        borderRadius: 2,
        alignSelf: 'stretch',
        minHeight: 40,
    },
    phaseCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.sm,
        marginBottom: 4,
        flexWrap: 'wrap',
    },
    phaseCardLabel: {
        fontSize: 14,
        fontFamily: FONT_FAMILY.semiBold,
    },
    phaseCardWhen: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: RADIUS.full,
    },
    phaseCardWhenText: {
        fontSize: 11,
        fontFamily: FONT_FAMILY.semiBold,
    },
    phaseCardDesc: {
        fontSize: 13,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        lineHeight: 19,
    },
    introNote: {
        flexDirection: 'row',
        backgroundColor: COLORS.accentLight,
        borderRadius: RADIUS.lg,
        padding: SPACING.md,
        gap: SPACING.sm,
        alignItems: 'flex-start',
    },
    introNoteIcon: { fontSize: 18 },
    introNoteText: {
        flex: 1,
        fontSize: 13,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.secondary,
        lineHeight: 20,
    },

    // ── Form elements ─────────────────────────────────────────────
    input: {
        backgroundColor: COLORS.surface,
        borderRadius: RADIUS.md,
        padding: SPACING.md,
        fontSize: 16,
        fontFamily: FONT_FAMILY.regular,
        color: COLORS.text.primary,
        borderWidth: 1,
        borderColor: COLORS.border,
        ...SHADOWS.sm,
    },
    textArea: { height: 100, textAlignVertical: 'top' },
    toggleRow: { flexDirection: 'row', gap: SPACING.sm },
    toggleOption: {
        flex: 1, padding: SPACING.md, backgroundColor: COLORS.surface,
        borderRadius: RADIUS.md, alignItems: 'center', borderWidth: 1, borderColor: COLORS.border,
    },
    toggleOptionActive: { backgroundColor: COLORS.accentLight, borderColor: COLORS.accent },
    toggleText: { fontFamily: FONT_FAMILY.semiBold, fontSize: 14, color: COLORS.text.secondary },
    toggleTextActive: { color: COLORS.accent },
    suggestionRow: {
        flexDirection: 'row', alignItems: 'center', padding: SPACING.md,
        backgroundColor: COLORS.surface, borderRadius: RADIUS.md, gap: SPACING.sm,
        borderWidth: 1, borderColor: COLORS.border, ...SHADOWS.sm,
    },
    suggestionRowActive: { borderColor: COLORS.accent, backgroundColor: COLORS.accentLight },
    suggestionRowDisabled: { opacity: 0.5 },
    suggestionName: { fontSize: 15, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary },
    suggestionSub: { fontSize: 12, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, marginTop: 2 },
    riskBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: RADIUS.full },
    riskText: { fontSize: 12, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary },
    infoBox: { backgroundColor: COLORS.accentLight, borderRadius: RADIUS.md, padding: SPACING.md },
    infoText: { fontSize: 13, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, lineHeight: 20 },

    // ── Plan preview ──────────────────────────────────────────────
    errorBox: { backgroundColor: 'rgba(217, 130, 126, 0.14)', borderRadius: RADIUS.md, padding: SPACING.md, gap: SPACING.sm, borderWidth: 1, borderColor: 'rgba(217, 130, 126, 0.34)' },
    errorText: { fontSize: 14, fontFamily: FONT_FAMILY.regular, color: COLORS.error, lineHeight: 20 },
    warningBox: { backgroundColor: 'rgba(212, 175, 55, 0.14)', borderRadius: RADIUS.md, padding: SPACING.md, gap: SPACING.sm, borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.30)' },
    warningText: { fontSize: 13, fontFamily: FONT_FAMILY.regular, color: COLORS.text.primary, lineHeight: 20 },
    planSummaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm },
    planStat: {
        width: '31%', backgroundColor: COLORS.surface, borderRadius: RADIUS.md,
        padding: SPACING.md, alignItems: 'center', ...SHADOWS.sm,
    },
    planStatValue: { fontSize: 18, fontFamily: FONT_FAMILY.black, color: COLORS.text.primary },
    planStatLabel: { fontSize: 11, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary, marginTop: 2, textAlign: 'center' },
    phaseBreakdown: { gap: SPACING.sm },
    phaseRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, backgroundColor: COLORS.surface, borderRadius: RADIUS.md, padding: SPACING.md },
    phaseColor: { width: 4, height: 40, borderRadius: 2 },
    phaseName: { fontSize: 14, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary },
    phaseDates: { fontSize: 12, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, marginTop: 2 },

    // ── Confirmation ──────────────────────────────────────────────
    confirmBox: {
        flexDirection: 'row', backgroundColor: 'rgba(183, 217, 168, 0.12)', borderRadius: RADIUS.md,
        padding: SPACING.md, gap: SPACING.sm, alignItems: 'flex-start',
        borderWidth: 1, borderColor: 'rgba(183, 217, 168, 0.32)',
    },
    confirmText: { flex: 1, fontSize: 14, fontFamily: FONT_FAMILY.regular, color: COLORS.text.primary, lineHeight: 22 },

    // ── Footer ────────────────────────────────────────────────────
    footer: {
        padding: SPACING.lg,
        paddingBottom: SPACING.lg,
        backgroundColor: 'rgba(10, 10, 10, 0.92)',
        borderTopWidth: 1,
        borderTopColor: COLORS.borderLight,
    },
    nextButton: { backgroundColor: COLORS.accent, borderRadius: RADIUS.full, padding: SPACING.md, alignItems: 'center', ...SHADOWS.colored.accent },
    nextButtonDisabled: { backgroundColor: COLORS.text.tertiary },
    activateButton: { backgroundColor: COLORS.accent, borderRadius: RADIUS.full, padding: SPACING.md, alignItems: 'center', ...SHADOWS.colored.accent },
    nextButtonText: { fontSize: 16, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.inverse },

    // ── Unsafe body-mass request disclaimer ───────────────────────
    extremeWarningBox: {
        backgroundColor: 'rgba(28, 10, 10, 0.82)', borderRadius: RADIUS.xl,
        borderWidth: 2, borderColor: COLORS.error,
        padding: SPACING.md, marginBottom: SPACING.md, gap: SPACING.xs,
    },
    extremeWarningHeader: { flexDirection: 'row', alignItems: 'center', gap: SPACING.xs, marginBottom: SPACING.xs },
    extremeWarningIcon: { fontSize: 22 },
    extremeWarningTitle: { fontFamily: FONT_FAMILY.semiBold, fontSize: 14, color: COLORS.error, letterSpacing: 0.4, flex: 1 },
    extremeWarningSubheading: { fontFamily: FONT_FAMILY.semiBold, fontSize: 13, color: COLORS.error, marginTop: SPACING.xs },
    extremeWarningBody: { fontFamily: FONT_FAMILY.regular, fontSize: 13, color: COLORS.text.secondary, lineHeight: 20 },
    extremeRiskItem: { fontFamily: FONT_FAMILY.regular, fontSize: 13, color: COLORS.error, paddingLeft: SPACING.xs, lineHeight: 20 },
    ackRow: {
        flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.sm, marginTop: SPACING.sm,
        backgroundColor: 'rgba(217, 130, 126, 0.14)', borderRadius: RADIUS.lg,
        padding: SPACING.sm, borderWidth: 1, borderColor: COLORS.error,
    },
    ackCheckbox: {
        width: 22, height: 22, borderRadius: 4, borderWidth: 2, borderColor: COLORS.error,
        justifyContent: 'center', alignItems: 'center', marginTop: 1, flexShrink: 0,
    },
    ackCheckboxChecked: { backgroundColor: COLORS.error, borderColor: COLORS.error },
    ackCheckmark: { fontFamily: FONT_FAMILY.semiBold, fontSize: 13, color: COLORS.text.primary },
    ackText: { flex: 1, fontFamily: FONT_FAMILY.regular, fontSize: 12, color: COLORS.text.secondary, lineHeight: 18 },
    extremeReminderBanner: {
        backgroundColor: 'rgba(217, 130, 126, 0.14)', borderRadius: RADIUS.lg,
        borderWidth: 1, borderColor: 'rgba(217, 130, 126, 0.34)', padding: SPACING.sm, marginBottom: SPACING.md,
    },
    extremeReminderText: { fontFamily: FONT_FAMILY.semiBold, fontSize: 13, color: COLORS.error, textAlign: 'center' },
});

