export type {
  AutoRegulateSCInput,
  AutoRegulateSCResult,
  CampSCModifier,
  ConditioningExercise,
  ConditioningPrescription,
  ConditioningType,
  EquipmentItem,
  ExerciseAdjustment,
  ExerciseHistoryEntry,
  ExerciseLibraryRow,
  ExerciseScoringContext,
  GenerateWorkoutInput,
  GenerateWorkoutInputV2,
  GymProfileRow,
  OverloadInput,
  OverloadSuggestion,
  PrescribedExercise,
  PrescribedExerciseV2,
  ProgressionModel,
  RestTimerConfig,
  RoadWorkInterval,
  RoadWorkPrescription,
  RoadWorkType,
  SetCompletionInput,
  WarmupInput,
  WarmupResult,
  WarmupSet,
  WorkoutLogRow,
  WorkoutPrescription,
  WorkoutPrescriptionV2,
  WorkoutSetLogRow
} from './legacy';

