import type { WorkoutProgrammingPreviewRequest } from './workoutProgrammingService.ts';

export const workoutProgrammingServiceFixtures = {
  beginnerBodyweightStrength: {
    goalId: 'beginner_strength',
    durationMinutes: 30,
    preferredDurationMinutes: 30,
    equipmentIds: ['bodyweight', 'mat'],
    experienceLevel: 'beginner',
    readinessBand: 'green',
    workoutEnvironment: 'home',
    preferredToneVariant: 'beginner_friendly',
  },
  dumbbellHypertrophy: {
    goalId: 'dumbbell_hypertrophy',
    durationMinutes: 45,
    preferredDurationMinutes: 45,
    equipmentIds: ['bodyweight', 'dumbbells', 'bench'],
    experienceLevel: 'intermediate',
    readinessBand: 'green',
    workoutEnvironment: 'gym',
    preferredToneVariant: 'coach_like',
  },
  zone2Cardio: {
    goalId: 'zone2_cardio',
    durationMinutes: 40,
    preferredDurationMinutes: 40,
    equipmentIds: ['bodyweight', 'stationary_bike'],
    experienceLevel: 'beginner',
    readinessBand: 'yellow',
    workoutEnvironment: 'gym',
    preferredToneVariant: 'data_driven',
  },
  lowImpactHiit: {
    goalId: 'low_impact_conditioning',
    durationMinutes: 28,
    preferredDurationMinutes: 28,
    equipmentIds: ['bodyweight', 'stationary_bike', 'sled'],
    experienceLevel: 'intermediate',
    readinessBand: 'green',
    safetyFlags: ['low_impact_required'],
    workoutEnvironment: 'gym',
    preferredToneVariant: 'athletic',
  },
  mobility: {
    goalId: 'mobility',
    durationMinutes: 25,
    preferredDurationMinutes: 25,
    equipmentIds: ['bodyweight', 'mat'],
    experienceLevel: 'beginner',
    readinessBand: 'yellow',
    workoutEnvironment: 'home',
    preferredToneVariant: 'rehab_informed',
  },
  recovery: {
    goalId: 'recovery',
    durationMinutes: 20,
    preferredDurationMinutes: 20,
    equipmentIds: ['bodyweight', 'mat'],
    experienceLevel: 'beginner',
    readinessBand: 'orange',
    safetyFlags: ['poor_readiness'],
    workoutEnvironment: 'home',
    preferredToneVariant: 'minimal',
  },
  balance: {
    goalId: 'core_durability',
    durationMinutes: 25,
    preferredDurationMinutes: 25,
    equipmentIds: ['bodyweight', 'chair'],
    experienceLevel: 'beginner',
    readinessBand: 'yellow',
    safetyFlags: ['fall_risk'],
    workoutEnvironment: 'home',
    preferredToneVariant: 'clinical',
  },
  power: {
    goalId: 'boxing_support',
    durationMinutes: 35,
    preferredDurationMinutes: 35,
    equipmentIds: ['bodyweight', 'medicine_ball', 'open_space'],
    experienceLevel: 'advanced',
    readinessBand: 'green',
    workoutEnvironment: 'gym',
    preferredToneVariant: 'athletic',
  },
} satisfies Record<string, WorkoutProgrammingPreviewRequest>;
