import {
  completeGeneratedWorkoutSession,
  loadGeneratedWorkoutCompletionSurfacesForUser,
  logWorkoutCompletion,
} from './workoutCompletionService.ts';
import { getWorkoutDescription } from './workoutDescriptionFacade.ts';
import {
  abandonGeneratedWorkoutSession,
  completeGeneratedWorkoutSessionLifecycle,
  generateGeneratedWorkoutSessionForUser,
  generatePreviewWorkout,
  generatePreviewWorkoutFromPerformanceState,
  generateWorkoutForUser,
  generateWorkoutForUserFromPerformanceState,
  getWorkoutProgrammingCatalog,
  listActiveGeneratedWorkoutSessions,
  loadActiveGeneratedWorkoutSession,
  loadGeneratedWorkoutForUser,
  markGeneratedWorkoutInspected,
  pauseGeneratedWorkoutSession,
  resumeGeneratedWorkoutSession,
  startGeneratedWorkoutSession,
  stopGeneratedWorkoutSession,
  validateWorkout,
} from './workoutGenerationService.ts';
import {
  archiveGeneratedProgramForUser,
  attachGeneratedWorkoutToProgramSessionForUser,
  generateWeeklyProgramForUser,
  generateWeeklyProgramFromPerformanceState,
  listGeneratedProgramsForUser,
  loadGeneratedProgramForUser,
  markGeneratedProgramSessionCompletedForUser,
  saveGeneratedProgramForUser,
  updateGeneratedProgramSessionForUser,
} from './workoutProgramService.ts';
import { getNextProgression } from './workoutProgressionService.ts';
import { substituteExercise } from './workoutSubstitutionService.ts';

export type {
  GeneratedWorkoutLifecycleResult,
  GeneratedWorkoutSessionCompletionInput,
  GeneratedWorkoutSessionCompletionResult,
  GeneratedWorkoutSessionExerciseCompletionInput,
  GeneratedWorkoutSessionResult,
  LogWorkoutCompletionOptions,
  ProgressionLookupOptions,
  WorkoutProgrammingCompletionResult,
  WorkoutProgrammingPerformanceStateRequest,
  WorkoutProgrammingPreviewRequest,
  WorkoutProgrammingProgramRequest,
  WorkoutProgrammingServiceOptions,
  WorkoutProgrammingSubstitutionConstraints,
  WorkoutProgrammingSubstitutionResult,
  WorkoutProgrammingUserRequest,
} from './workoutProgrammingServiceTypes.ts';

export {
  completeGeneratedWorkoutSession,
  loadGeneratedWorkoutCompletionSurfacesForUser,
  logWorkoutCompletion,
} from './workoutCompletionService.ts';
export { getWorkoutDescription } from './workoutDescriptionFacade.ts';
export {
  abandonGeneratedWorkoutSession,
  completeGeneratedWorkoutSessionLifecycle,
  generateGeneratedWorkoutSessionForUser,
  generatePreviewWorkout,
  generatePreviewWorkoutFromPerformanceState,
  generateWorkoutForUser,
  generateWorkoutForUserFromPerformanceState,
  getWorkoutProgrammingCatalog,
  listActiveGeneratedWorkoutSessions,
  loadActiveGeneratedWorkoutSession,
  loadGeneratedWorkoutForUser,
  markGeneratedWorkoutInspected,
  pauseGeneratedWorkoutSession,
  resumeGeneratedWorkoutSession,
  startGeneratedWorkoutSession,
  stopGeneratedWorkoutSession,
  validateWorkout,
} from './workoutGenerationService.ts';
export {
  archiveGeneratedProgramForUser,
  attachGeneratedWorkoutToProgramSessionForUser,
  generateWeeklyProgramForUser,
  generateWeeklyProgramFromPerformanceState,
  listGeneratedProgramsForUser,
  loadGeneratedProgramForUser,
  markGeneratedProgramSessionCompletedForUser,
  saveGeneratedProgramForUser,
  updateGeneratedProgramSessionForUser,
} from './workoutProgramService.ts';
export { getNextProgression } from './workoutProgressionService.ts';
export { substituteExercise } from './workoutSubstitutionService.ts';

export const workoutProgrammingService = {
  getWorkoutProgrammingCatalog,
  generateWorkoutForUser,
  generateGeneratedWorkoutSessionForUser,
  markGeneratedWorkoutInspected,
  startGeneratedWorkoutSession,
  pauseGeneratedWorkoutSession,
  resumeGeneratedWorkoutSession,
  abandonGeneratedWorkoutSession,
  stopGeneratedWorkoutSession,
  completeGeneratedWorkoutSessionLifecycle,
  loadActiveGeneratedWorkoutSession,
  listActiveGeneratedWorkoutSessions,
  generatePreviewWorkout,
  generatePreviewWorkoutFromPerformanceState,
  generateWorkoutForUserFromPerformanceState,
  validateWorkout,
  substituteExercise,
  logWorkoutCompletion,
  completeGeneratedWorkoutSession,
  getNextProgression,
  loadGeneratedWorkoutCompletionSurfacesForUser,
  generateWeeklyProgramForUser,
  loadGeneratedWorkoutForUser,
  saveGeneratedProgramForUser,
  loadGeneratedProgramForUser,
  listGeneratedProgramsForUser,
  updateGeneratedProgramSessionForUser,
  attachGeneratedWorkoutToProgramSessionForUser,
  markGeneratedProgramSessionCompletedForUser,
  archiveGeneratedProgramForUser,
  generateWeeklyProgramFromPerformanceState,
  getWorkoutDescription,
};
