import { StyleSheet } from 'react-native';

import { COLORS, FONT_FAMILY, RADIUS, SHADOWS, SPACING, TYPOGRAPHY_V2, BORDERS } from '../../theme/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: 'transparent' },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'transparent' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.lg, paddingTop: SPACING.md, paddingBottom: SPACING.sm },
  backButton: { minWidth: 64, paddingVertical: SPACING.xs },
  backButtonText: { fontSize: 16, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary },
  headerTitle: { ...TYPOGRAPHY_V2.plan.headline, color: COLORS.text.primary },
  headerRight: { minWidth: 64, alignItems: 'flex-end' },
  progressShell: { marginHorizontal: SPACING.lg, marginBottom: SPACING.md, backgroundColor: 'rgba(10, 10, 10, 0.68)', borderRadius: RADIUS.xl, padding: SPACING.lg, borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.22)', ...SHADOWS.card },
  progressHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: SPACING.xs },
  progressEyebrow: { ...TYPOGRAPHY_V2.plan.caption, fontSize: 11, color: COLORS.text.tertiary, textTransform: 'uppercase', letterSpacing: 1.2 },
  progressCount: { ...TYPOGRAPHY_V2.plan.caption, color: COLORS.text.tertiary },
  phaseTitle: { ...TYPOGRAPHY_V2.plan.title, color: COLORS.text.primary, marginBottom: SPACING.xs },
  phaseDescription: { ...TYPOGRAPHY_V2.plan.body, color: COLORS.text.secondary, marginBottom: SPACING.md },
  progressTrack: { height: 6, borderRadius: RADIUS.full, backgroundColor: COLORS.borderLight, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: RADIUS.full, backgroundColor: COLORS.accent },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.xs, paddingBottom: SPACING.xxxl, gap: SPACING.md },
  section: { backgroundColor: COLORS.surface, borderRadius: RADIUS.xl, padding: SPACING.lg, ...SHADOWS.card, ...BORDERS.card },
  sectionLabel: { ...TYPOGRAPHY_V2.plan.caption, fontSize: 11, color: COLORS.text.tertiary, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: SPACING.xs },
  sectionDescription: { ...TYPOGRAPHY_V2.plan.body, color: COLORS.text.secondary, marginBottom: SPACING.sm },
  subLabel: { ...TYPOGRAPHY_V2.plan.headline, fontSize: 18, color: COLORS.text.primary, marginTop: SPACING.md },
  fieldNote: { ...TYPOGRAPHY_V2.plan.caption, color: COLORS.text.tertiary, marginTop: SPACING.xs },
  dateRow: { paddingRight: SPACING.lg, paddingTop: SPACING.sm },
  datePill: { width: 72, height: 72, borderRadius: RADIUS.md, borderWidth: 1, marginRight: SPACING.sm, alignItems: 'center', justifyContent: 'center' },
  datePillSelected: { backgroundColor: 'rgba(212, 175, 55, 0.16)', borderColor: COLORS.accent, ...SHADOWS.colored.accent },
  datePillIdle: { backgroundColor: COLORS.surface, borderColor: COLORS.borderLight },
  dateTopText: { fontSize: 12, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary, marginBottom: 4 },
  dateBottomText: { fontSize: 16, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary },
  dayRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm, marginTop: SPACING.sm },
  dayPill: { minWidth: 58, alignItems: 'center', justifyContent: 'center', paddingVertical: SPACING.sm, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.surface },
  dayPillSelected: { borderColor: COLORS.accent, backgroundColor: 'rgba(212, 175, 55, 0.16)', ...SHADOWS.colored.accent },
  dayPillText: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary },
  optionList: { gap: SPACING.sm, marginTop: SPACING.sm },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm, marginTop: SPACING.sm },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm + 4,
  },
  optionCardSelected: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(212, 175, 55, 0.10)',
    ...SHADOWS.colored.accent,
  },
  optionCardText: {
    ...TYPOGRAPHY_V2.plan.body,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  optionCardTextSelected: {
    color: COLORS.accent,
  },
  optionCardIndicator: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionCardIndicatorSelected: {
    borderColor: COLORS.accent,
    backgroundColor: COLORS.accent,
  },
  optionPill: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.surface },
  optionPillSelected: { borderColor: COLORS.accent, backgroundColor: 'rgba(212, 175, 55, 0.16)', ...SHADOWS.colored.accent },
  optionPillText: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary },
  optionPillTextSelected: { color: COLORS.accent },
  advancedToggle: { marginTop: SPACING.lg, borderWidth: 1, borderColor: COLORS.borderLight, borderRadius: RADIUS.md, padding: SPACING.md, backgroundColor: COLORS.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  advancedToggleTextWrap: { flex: 1, paddingRight: SPACING.md },
  advancedToggleTitle: { ...TYPOGRAPHY_V2.plan.headline, fontSize: 16, color: COLORS.text.primary, marginBottom: 2 },
  advancedToggleDescription: { ...TYPOGRAPHY_V2.plan.caption, color: COLORS.text.secondary },
  advancedToggleAction: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.accent },
  input: { marginTop: SPACING.sm, borderWidth: 1, borderColor: COLORS.borderLight, borderRadius: RADIUS.md, paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, ...TYPOGRAPHY_V2.plan.body, color: COLORS.text.primary, backgroundColor: COLORS.surface },
  multilineInput: { minHeight: 96, textAlignVertical: 'top' },
  inputRow: { flexDirection: 'row', alignItems: 'flex-start' },
  inlineField: { flex: 1 },
  dropdownField: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownFieldText: { ...TYPOGRAPHY_V2.plan.body, color: COLORS.text.primary },
  dropdownFieldChevron: { fontSize: 14, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.tertiary },
  windowCard: { marginTop: SPACING.md, borderWidth: 1, borderColor: COLORS.borderLight, borderRadius: RADIUS.md, padding: SPACING.md, backgroundColor: COLORS.surface },
  windowTitle: { ...TYPOGRAPHY_V2.plan.headline, fontSize: 16, color: COLORS.text.primary, marginBottom: SPACING.xs },
  commitmentCard: { marginTop: SPACING.md, borderWidth: 1, borderColor: COLORS.borderLight, borderRadius: RADIUS.md, padding: SPACING.md, backgroundColor: COLORS.surface },
  commitmentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  commitmentTitle: { ...TYPOGRAPHY_V2.plan.headline, fontSize: 16, color: COLORS.text.primary },
  removeText: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.readiness.depleted },
  toggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: SPACING.md },
  toggleLabel: { flex: 1, marginRight: SPACING.md, ...TYPOGRAPHY_V2.plan.body, fontWeight: '600', color: COLORS.text.primary },
  previewCard: { marginTop: SPACING.lg, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.borderLight, backgroundColor: COLORS.surface, padding: SPACING.md, gap: SPACING.xs },
  previewTitle: { ...TYPOGRAPHY_V2.plan.caption, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.2, color: COLORS.text.tertiary, marginBottom: 4 },
  previewLine: { ...TYPOGRAPHY_V2.plan.body, fontSize: 14, color: COLORS.text.secondary },
  secondaryButton: { marginTop: SPACING.lg, borderRadius: RADIUS.full, borderWidth: 1, borderColor: COLORS.accent, paddingVertical: SPACING.md, alignItems: 'center', backgroundColor: 'rgba(212, 175, 55, 0.06)' },
  secondaryButtonText: { fontSize: 15, fontFamily: FONT_FAMILY.semiBold, color: COLORS.accent },
  
  saveBarContainer: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.md, backgroundColor: 'transparent' }, 
  saveButtonWrap: { borderRadius: RADIUS.full, overflow: 'hidden', ...SHADOWS.colored.accent },
  saveButtonBg: { height: 56, alignItems: 'center', justifyContent: 'center' },
  saveButtonDisabled: { opacity: 0.5 },
  saveButtonText: { fontSize: 16, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.inverse, letterSpacing: 0.5 },
  
  durationPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 10, 10, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.lg,
  },
  durationPickerSheet: {
    width: '100%',
    maxWidth: 360,
    borderRadius: RADIUS.xl,
    backgroundColor: 'rgba(10, 10, 10, 0.94)',
    padding: SPACING.md,
    ...SHADOWS.cardElevated,
    ...BORDERS.elevated,
  },
  durationPickerTitle: {
    ...TYPOGRAPHY_V2.plan.headline,
    color: COLORS.text.primary,
    marginBottom: SPACING.sm,
  },
  durationPickerOption: {
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surface,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.xs,
  },
  durationPickerOptionSelected: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(212, 175, 55, 0.16)',
  },
  durationPickerOptionText: {
    fontSize: 15,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  durationPickerOptionTextSelected: {
    color: COLORS.accent,
  },
  durationPickerCancel: {
    marginTop: SPACING.sm,
    alignItems: 'center',
    paddingVertical: SPACING.sm,
  },
  durationPickerCancelText: {
    fontSize: 15,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
  },
});
