import { StyleSheet } from 'react-native';

import { COLORS, FONT_FAMILY, RADIUS, SHADOWS, SPACING } from '../../theme/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.background },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.background },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.lg, paddingTop: SPACING.md, paddingBottom: SPACING.sm },
  backButton: { minWidth: 64, paddingVertical: SPACING.xs },
  backButtonText: { fontSize: 15, fontFamily: FONT_FAMILY.semiBold, color: COLORS.readiness.prime },
  headerTitle: { fontSize: 18, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary },
  headerRight: { minWidth: 64, alignItems: 'flex-end' },
  progressShell: { marginHorizontal: SPACING.lg, marginBottom: SPACING.md, backgroundColor: COLORS.surface, borderRadius: RADIUS.xl, padding: SPACING.lg, ...SHADOWS.card },
  progressHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: SPACING.xs },
  progressEyebrow: { fontSize: 12, fontFamily: FONT_FAMILY.semiBold, color: COLORS.readiness.prime, textTransform: 'uppercase', letterSpacing: 0.8 },
  progressCount: { fontSize: 12, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.tertiary },
  phaseTitle: { fontSize: 24, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary, marginBottom: SPACING.xs },
  phaseDescription: { fontSize: 14, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, lineHeight: 21, marginBottom: SPACING.md },
  progressTrack: { height: 6, borderRadius: RADIUS.full, backgroundColor: COLORS.border, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: RADIUS.full, backgroundColor: COLORS.readiness.prime },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: SPACING.lg, paddingTop: SPACING.xs, gap: SPACING.sm },
  section: { backgroundColor: COLORS.surface, borderRadius: RADIUS.xl, padding: SPACING.lg, ...SHADOWS.card },
  sectionLabel: { fontSize: 12, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: SPACING.xs },
  sectionDescription: { fontSize: 14, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, lineHeight: 20, marginBottom: SPACING.sm },
  subLabel: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary, marginTop: SPACING.md },
  fieldNote: { fontSize: 12, fontFamily: FONT_FAMILY.regular, color: COLORS.text.tertiary, lineHeight: 18, marginTop: SPACING.xs },
  dateRow: { paddingRight: SPACING.lg, paddingTop: SPACING.sm },
  datePill: { width: 72, height: 72, borderRadius: RADIUS.md, borderWidth: 1.5, marginRight: SPACING.sm, alignItems: 'center', justifyContent: 'center' },
  datePillSelected: { backgroundColor: COLORS.readiness.prime, borderColor: COLORS.readiness.prime },
  datePillIdle: { backgroundColor: COLORS.surfaceSecondary, borderColor: COLORS.border },
  dateTopText: { fontSize: 11, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary, marginBottom: 4 },
  dateBottomText: { fontSize: 13, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary },
  dayRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm, marginTop: SPACING.sm },
  dayPill: { minWidth: 58, alignItems: 'center', justifyContent: 'center', paddingVertical: SPACING.sm, borderRadius: RADIUS.md, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: COLORS.surfaceSecondary },
  dayPillSelected: { borderColor: COLORS.readiness.prime, backgroundColor: COLORS.readiness.prime },
  dayPillText: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.secondary },
  optionList: { gap: SPACING.sm, marginTop: SPACING.sm },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm, marginTop: SPACING.sm },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: RADIUS.lg,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceSecondary,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm + 2,
  },
  optionCardSelected: {
    borderColor: COLORS.readiness.prime,
    backgroundColor: COLORS.readiness.primeLight,
  },
  optionCardText: {
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  optionCardTextSelected: {
    color: COLORS.readiness.prime,
  },
  optionCardIndicator: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionCardIndicatorSelected: {
    borderColor: COLORS.readiness.prime,
    backgroundColor: '#FFFFFF',
  },
  optionPill: { paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, borderRadius: RADIUS.full, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: COLORS.surfaceSecondary },
  optionPillSelected: { borderColor: COLORS.readiness.prime, backgroundColor: COLORS.readiness.prime },
  optionPillText: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary },
  optionPillTextSelected: { color: '#FFFFFF' },
  advancedToggle: { marginTop: SPACING.lg, borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, backgroundColor: COLORS.surfaceSecondary, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  advancedToggleTextWrap: { flex: 1, paddingRight: SPACING.md },
  advancedToggleTitle: { fontSize: 14, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary, marginBottom: 2 },
  advancedToggleDescription: { fontSize: 12, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, lineHeight: 18 },
  advancedToggleAction: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.readiness.prime },
  input: { marginTop: SPACING.sm, borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, fontSize: 15, fontFamily: FONT_FAMILY.regular, color: COLORS.text.primary, backgroundColor: COLORS.surfaceSecondary },
  multilineInput: { minHeight: 96, textAlignVertical: 'top' },
  inputRow: { flexDirection: 'row', alignItems: 'flex-start' },
  inlineField: { flex: 1 },
  dropdownField: {
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surfaceSecondary,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownFieldText: { fontSize: 15, fontFamily: FONT_FAMILY.regular, color: COLORS.text.primary },
  dropdownFieldChevron: { fontSize: 14, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.tertiary },
  windowCard: { marginTop: SPACING.md, borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, backgroundColor: COLORS.surfaceSecondary },
  windowTitle: { fontSize: 14, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary, marginBottom: SPACING.xs },
  commitmentCard: { marginTop: SPACING.md, borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.md, backgroundColor: COLORS.surfaceSecondary },
  commitmentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  commitmentTitle: { fontSize: 14, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary },
  removeText: { fontSize: 13, fontFamily: FONT_FAMILY.semiBold, color: COLORS.readiness.depleted },
  toggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: SPACING.md },
  toggleLabel: { flex: 1, marginRight: SPACING.md, fontSize: 14, fontFamily: FONT_FAMILY.semiBold, color: COLORS.text.primary },
  previewCard: { marginTop: SPACING.lg, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.border, backgroundColor: COLORS.surfaceSecondary, padding: SPACING.md, gap: SPACING.xs },
  previewTitle: { fontSize: 13, fontFamily: FONT_FAMILY.extraBold, color: COLORS.text.primary, marginBottom: 2 },
  previewLine: { fontSize: 12, fontFamily: FONT_FAMILY.regular, color: COLORS.text.secondary, lineHeight: 17 },
  secondaryButton: { marginTop: SPACING.lg, borderRadius: RADIUS.md, borderWidth: 1, borderColor: COLORS.readiness.prime, paddingVertical: SPACING.md, alignItems: 'center' },
  secondaryButtonText: { fontSize: 14, fontFamily: FONT_FAMILY.semiBold, color: COLORS.readiness.prime },
  saveBar: { position: 'absolute', left: 0, right: 0, bottom: 0, borderTopWidth: 1, borderTopColor: COLORS.border, backgroundColor: COLORS.background, paddingHorizontal: SPACING.lg, paddingTop: SPACING.md },
  saveButton: { height: 52, borderRadius: RADIUS.md, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.readiness.prime, ...SHADOWS.card },
  saveButtonDisabled: { opacity: 0.6 },
  saveButtonText: { fontSize: 16, fontFamily: FONT_FAMILY.semiBold, color: '#FFFFFF' },
  durationPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.lg,
  },
  durationPickerSheet: {
    width: '100%',
    maxWidth: 360,
    borderRadius: RADIUS.xl,
    backgroundColor: COLORS.surface,
    padding: SPACING.md,
    ...SHADOWS.card,
  },
  durationPickerTitle: {
    fontSize: 16,
    fontFamily: FONT_FAMILY.extraBold,
    color: COLORS.text.primary,
    marginBottom: SPACING.sm,
  },
  durationPickerOption: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.surfaceSecondary,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.xs,
  },
  durationPickerOptionSelected: {
    borderColor: COLORS.readiness.prime,
    backgroundColor: COLORS.readiness.primeLight,
  },
  durationPickerOptionText: {
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.primary,
  },
  durationPickerOptionTextSelected: {
    color: COLORS.readiness.prime,
  },
  durationPickerCancel: {
    marginTop: SPACING.sm,
    alignItems: 'center',
    paddingVertical: SPACING.sm,
  },
  durationPickerCancelText: {
    fontSize: 14,
    fontFamily: FONT_FAMILY.semiBold,
    color: COLORS.text.tertiary,
  },
});
